---
title: "Task 3: Urban Change"
author: "Marie Bouffard"
date: "11/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# Attach packages
library(tidyverse)
library(janitor)
library(here)
library(kableExtra)

# Read in urban area change data
urban_change <- read.csv(here("Data", "3_UrbanAreas_Change.csv")) %>% 
  clean_names()

# Read in riparian data
riparian_county <- read.csv((here("Data", "3_riparian_county_2018.csv"))) %>% 
  clean_names() %>% 
   mutate(i_county = as.factor(i_county))

# County Pallet
county_pallette <- c("#68affc", "#485172", "#d6a7f0", "#7c46a0", "#20d8fd", "#155126", "#a2e84f", "#528f7a", "#7dd9a0", "#39970e", "#d0d9ae", "#e27040", "#f29180", "#e13224", "#922d4c", "#d9c937", "#fa217f", "#36f459", "#b825af", "#f27ff5", "#fda547", "#b7358d", "#a1e8af", "#7e52a0")

```

Riparian Buffer Percent Tree Canopy over land area
```{r}
#---------------------------------------
# Percent Tree Canopy over land area
#---------------------------------------

riparian_buffer_plot <- ggplot(data = riparian_county, aes(x = fct_rev(i_county), y = can_p_land)) +
  geom_col(aes(fill = i_county), alpha = 0.8) +
  labs(
    title = "Riparian Buffer Percent Tree Canopy",
    x = "Jurisdiction",
    y = "Percent Tree Canopy over Land Area") +
  scale_fill_manual(values = county_pallette) +
  geom_text(label = "70%",
            color = "red",
            face = "bold",
            vjust = 12.85,
            aes(x = "Montgomery",y = 70)) +
  geom_hline(aes(yintercept = 70), linetype = "dashed",
            color = "red",
            size = 1) +
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  coord_flip(clip = "off") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    legend.position = "none"
  )

riparian_buffer_plot

ggsave(here("Graphics", "3_riparian_percent.jpg"), riparian_buffer_plot)


```

```{r}

#---------------------------------------
# Riparian buffer threshold alternate color schemes
#---------------------------------------

# Create new variable: above or below threshold
riparian_threshold <- riparian_county %>% 
  mutate(threshold = case_when(
    can_p_land >= 70 ~ "Meets Goal",
    can_p_land < 70 ~ "Does Not Meet Goal"
  ))

# Different opacity and colors for meet or do not meet threshold
#---------------------------------------
ggplot(data = riparian_threshold, aes(x = fct_rev(i_county), y = can_p_land)) +
  geom_col(aes(alpha = threshold), fill = "seagreen4") +
  scale_alpha_manual(values = c(0.3, 0.9)) +
  labs(
    title = "Riparian Buffer Percent Tree Canopy",
    x = "Jurisdiction",
    y = "Percent Tree Canopy over Land Area") +
  geom_text(label = "70%",
            color = "red",
            face = "bold",
            vjust = 12.85,
            aes(x = "Montgomery",y = 70)) +
  geom_hline(aes(yintercept = 70), linetype = "dashed",
            color = "red",
            size = 1) +
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  coord_flip(clip = "off") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    legend.position = "none"
  )

# semi-transparent counties under threshold
#---------------------------------------
save_the_colors <- ggplot(data = riparian_threshold, aes(x = fct_rev(i_county), y = can_p_land)) +
  geom_col(aes(fill = i_county, color = i_county, alpha = threshold)) +
  scale_color_manual(values = county_pallette) +
  scale_fill_manual(values = county_pallette) +
  scale_alpha_manual(values = c(0.3, 1)) +
  labs(
    title = "Riparian Buffer Percent Tree Canopy",
    x = "Jurisdiction",
    y = "Percent Tree Canopy over Land Area") +
  geom_text(label = "70%",
            color = "red",
            face = "bold",
            vjust = 12.85,
            aes(x = "Montgomery",y = 70)) +
  geom_hline(aes(yintercept = 70), linetype = "dashed",
            color = "red",
            size = 1) +
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  coord_flip(clip = "off") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    legend.position = "none"
  )

ggsave(here("Graphics", "save_the_colors.jpg"), save_the_colors)

# highlight passing counties
#---------------------------------------
ggplot(data = riparian_threshold, aes(x = fct_rev(i_county), y = can_p_land)) +
  geom_col(aes(fill = i_county)) +
  scale_fill_manual(values = county_pallette) +
  gghighlight::gghighlight(threshold == "Meets Goal") +
  labs(
    title = "Riparian Buffer Percent Tree Canopy",
    x = "Jurisdiction",
    y = "Percent Tree Canopy over Land Area") +
  geom_text(label = "70%",
            color = "red",
            face = "bold",
            vjust = 12.85,
            aes(x = "Montgomery",y = 70)) +
  geom_hline(aes(yintercept = 70), linetype = "dashed",
            color = "red",
            size = 1) +
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  coord_flip(clip = "off") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    legend.position = "none"
  )

# Option 1: Different colors
#---------------------------------------
new_riparian_1 <- ggplot(data = riparian_threshold, aes(x = fct_rev(i_county), y = can_p_land)) +
  geom_col(aes(fill = threshold)) +
  scale_fill_manual(values = c("#c3dbcb", "seagreen4")) +
  labs(
    title = "Riparian Buffer Percent Tree Canopy",
    x = "Jurisdiction",
    y = "Percent Tree Canopy \n over Land Area") +
  geom_text(label = "70%",
            color = "red",
            face = "bold",
            vjust = 12.85,
            aes(x = "Harford",y = 70)) +
  geom_hline(aes(yintercept = 70), linetype = "dashed",
            color = "red",
            size = 1) +
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  coord_flip(clip = "off") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title = element_blank()
  )

new_riparian_1

ggsave(here("Graphics", "3_riparian_new_option1.jpg"), new_riparian_1)

# Option 2: Grey out failed counties
#---------------------------------------

new_riparian_2 <- ggplot(data = riparian_threshold, aes(x = fct_rev(i_county), y = can_p_land)) +
  geom_col(aes(fill = threshold)) +
  scale_fill_manual(values = c("#d8d8d8", "seagreen4")) +
  labs(
    title = "Riparian Buffer Percent Tree Canopy",
    x = "Jurisdiction",
    y = "Percent Tree Canopy \n over Land Area") +
  geom_text(label = "70%",
            color = "red",
            face = "bold",
            vjust = 12.85,
            aes(x = "Harford",y = 70)) +
  geom_hline(aes(yintercept = 70), linetype = "dashed",
            color = "red",
            size = 1) +
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  coord_flip(clip = "off") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title = element_blank()
  )

new_riparian_2

ggsave(here("Graphics", "3_riparian_new_option2.jpg"), new_riparian_2)

```

Overview Stats
```{r}

#---------------------------------------
# Total Change
#---------------------------------------

# Calculate total area lost overall, 2013, 2018
tc_stats <- urban_change %>% 
  select(tc_change_acres:tc_acres2018) %>% 
    summarize(
    tc_all = sum(tc_change_acres),
    tc_2013 = max(tc_acres2013),
    tc_2018 = mean(tc_acres2018)
  )

# Make table
kable(tc_stats,
      col.names = c("Total Change",
                    "2013 Change",
                    "2018 Change")) %>%
  kable_paper(html_font = "Times")
#  save_kable(file = here("Graphics","3_TC_stats.png"), tc_stats) # Don't know what this isn't exporting an image

```

### UATYP10
```{r}

# Get total change for each urban area type
urban_type <- urban_change %>% 
  select(uatyp10, tc_change_acres) %>% 
  group_by(uatyp10) %>% 
    summarize(
    tc_all = sum(tc_change_acres),
  ) %>%
  mutate(uatyp10 = case_when(
    uatyp10 == "U" ~ "Urbanized Areas",
    uatyp10 == "C" ~ "Urbanized Clusters"))

# Plot
uatyp10_plot <- ggplot(urban_type, aes(x = uatyp10, y = tc_all)) +
geom_col(aes(fill = uatyp10)) +
  scale_fill_manual(values = c("#FF6B6B", "#7D82B8")) +
  labs(x = "Urban Area Type",
       y = "Change in Area (Acres)",
       title = "Total Change by Urban Area Type and Time Period") +
  scale_y_continuous(breaks = c(-10000, -5000, 0),
                     labels = c("-10,000", "-5,000", "0")) +
  theme_minimal() +
  geom_hline(aes(yintercept=0))+
  theme(
    plot.title = element_text(size = 16, family = "Times"),
    axis.title.y = element_text(size = 14, family = "Times"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 10, family = "Times"),
    axis.text.x = element_text(size = 16, family = "Times"),
    legend.position = "none"
    )

uatyp10_plot

ggsave(here("Graphics", "3_uatyp10.jpg"))

```

