---
title: "Task 1: Plantable Area"
author: "Marie Bouffard"
date: "11/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# Attach packages
library(tidyverse)
library(janitor)
library(here)
library(scales)

#1a.
# Read in 2018 state data
state_forest <- read.csv(here("Data", "1a_state_short_2018.csv")) %>% 
  clean_names()

# Read in 2018 county data
county_forest <- read.csv(here("Data", "1a_County_short_2018.csv")) %>% 
  clean_names()

# 1b.
# Read in Plantable Area data
plantable_county <- read.csv(here("Data", "1b_plantable_2018_county.csv")) %>% 
  clean_names() %>% 
  mutate(county = as.factor(county))

# Old csv with percent data
plantable_percent <- read.csv(here("Data", "1b_plantableareas_2018_county_full.csv")) %>% 
  clean_names() %>% 
  rename(county = county) %>% 
  mutate(county = as.factor(county))

# Plantable area stack
plantable_stack <- read.csv(here("Data", "1b_plantableareas_2018_county_stack.csv")) %>% 
  clean_names()

# Plantable dummy data
dummy_data <- read.csv(here("Data", "DummyData_populated.csv")) %>% 
  clean_names()

lc_pallette <- c("#6eb663", # Forest Canopy, light green
                 "#8DBE87", # Low veg, light green
                 "#F08701", # Impervious, orange 
                 "#21A0A0",  # Wetland, Blue-green
                 "#F9A620", # Roads, light orange
                 "#D9682A", # Buildings, brick
#                 "#24693d", # Forest, green
                 "#4059AD", # Water, royal blue
                 "#F9DB6D", # Barren, light yellow
                 "#57AF94" # Shrub, green-blue
                 )

lc_county_pallette <- c(
  "#6eb663", # Forest Canopy, light green
  "#8DBE87", # Low veg, light green
  "#F08701", # Impervious, orange 
  "#21A0A0",  # Wetland, Blue-green
  "#F9A620", # Roads, light orange
  "#D9682A", # Buildings, brick
  "#4059AD", # Water, royal blue
  "#F9DB6D", # Barren, light yellow
  "#57AF94" # Shrub, green-blue
)

# Plantable stack
plantable_pallete <- c(
  "#8DBE87", # Low veg, light green
  "#F9DB6D", # Barren, light yellow
  "#57AF94" # Shrub, green-blue
)

# Categorical County Color Pallette
county_pallette <- c("#68affc", "#485172", "#d6a7f0", "#7c46a0", "#20d8fd", "#155126", "#a2e84f", "#528f7a", "#7dd9a0", "#39970e", "#d0d9ae", "#e27040", "#f29180", "#e13224", "#922d4c", "#d9c937", "#fa217f", "#36f459", "#b825af", "#f27ff5", "#fda547", "#b7358d", "#a1e8af", "#7e52a0")

```

### Task 1a. 2018 forest stats

#### State Level
Tree canopy inside vs. outside forests
```{r}
#---------------------------------------
# 2018 statewide tree canopy inside vs. outside forest
#---------------------------------------
state_in_out <- state_forest %>% 
  select(tc_a_acres_inside_forest, tc_a_acres_outside_forest) %>% 
  pivot_longer(tc_a_acres_inside_forest:tc_a_acres_outside_forest,
               names_to = "type",
               values_to = "acres") %>% 
  mutate(type = case_when(
    type == "tc_a_acres_inside_forest" ~ "Inside Forest",
    type == "tc_a_acres_outside_forest" ~ "Outside Forest"))

# Plot
state_in_out_plot <- ggplot(data = state_in_out, aes(x = type, y = acres)) +
  geom_col(aes(fill = type)) +
  geom_text(aes(label = round(acres, digits = 0),
                color = type),
            vjust = -0.5) +
  scale_fill_manual(values = c("#24693d", "#6eb663")) +
  scale_color_manual(values = c("#24693d", "#6eb663")) +
  # geom_hline(aes(yintercept=0)) +
  # geom_vline(aes(xintercept=0)) +
  labs(title = "2018 Tree Canopy Inside and Outside Forests",
       y = "Tree Canopy Area (Acres)") +
  scale_y_continuous(breaks = c(0, 500000, 1000000, 1500000),
                     labels = c("0", "500,000", "1,000,000", "1,500,000")) +
  theme_minimal() +
  theme(
    text = element_text(family = "Times", size = 12),
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    legend.position = "none"
  )

state_in_out_plot

ggsave(here("Graphics", "1a_state_in_out_forest_2018.jpg"), state_in_out_plot, height = 6)

```
Other land use change
```{r}
#---------------------------------------
# 2018 statewide land cover change
#---------------------------------------
# Get percents 
state_lc_percent <- state_forest %>% 
  select(i_land_a:imperv_a_acres) %>% 
  pivot_longer(can_a_acres:imperv_a_acres, names_to = "lc", values_to = "acres") %>%
  mutate(lc = case_when(
#    lc == "i_total_a_acres" ~ "Total Acres",
    lc == "can_a_acres" ~ "Tree Canopy",
    lc == "low_veg_a_acres" ~ "Low Vegetation",
    lc == "barren_a_acres" ~ "Barren",
    lc == "water_a_acres" ~ "Water",
    lc == "build_a_acres" ~ "Building",
    lc == "road_a_acres" ~ "Road",
    lc == "imperv_a_acres" ~ "Impervious",
    lc == "wetlands_a_acres" ~ "Wetlands",
    lc == "shrub_a_acres" ~ "Shrub")) %>% 
  mutate(percent = acres/sum(acres),
         label = scales::percent(percent)) %>% 
  mutate(lc = fct_reorder(lc, desc(percent)))

state_lc_percent$state <- "Maryland"

# plot columns
#---------------------------------------
state_lc_percent_col <- ggplot(data = state_lc_percent, aes(x = lc, y = percent, label = label)) +
  geom_col(aes(fill = lc)) +
  geom_text(hjust = -0.1, color = "grey40", size = 3) +
  scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.65),
                     labels = c("0%", "10%", "20%", "30%", "40%", "50%", " ")) +
  scale_fill_manual(values = lc_pallette) +
  labs(x = "Land Use Type",
       y = "Percent of Land Cover") +
  coord_flip() +
  theme_minimal() +
  theme(
    text = element_text(family = "Times", size = 12),
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
#    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.position = "none"
  )

state_lc_percent_col

# ggsave(here("Graphics", "1a_state_lc_col.jpg"), state_lc_percent_col, width = 7.5, height = 4.5)

# plot stacked bar
#---------------------------------------
state_lc_percent_stack <- ggplot(data = state_lc_percent, aes(fill = lc, x = state, y = percent, label = label)) +
  geom_bar(position = "fill", stat = "identity") +
  geom_text(
#    vjust = -12, 
    hjust = -5, 
    size = 3,
    color = "white") +
  labs(
    title = "2018 Land Cover Proportions",
    y = "Percent State Land Cover") +
  scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1),
                     labels = c("0%", "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%")) +
  scale_fill_manual(values = lc_pallette) +
  coord_flip() +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_text(size = 14, margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.title = element_text(size = 14),
    legend.position = "top",
    legend.title.align = 0.5
  ) +
  guides(fill = guide_legend(title = "Land Cover Type",
                             title.position = "top"))

state_lc_percent_stack

ggsave(here("Graphics", "1a_state_lc_stack.jpg"), state_lc_percent_stack, width = 7.29, height = 3)

```
#### County Level
Tree canopy inside vs. outside forests
```{r}
#---------------------------------------
# 2018 tree canopy inside vs. outside forest by county
#---------------------------------------
county_in_out <- county_forest %>% 
  select(county, tc_a_acres_inside_forest, tc_a_acres_outside_forest) %>% 
  pivot_longer(!county, names_to = "type", values_to = "acres") %>% 
      mutate(type = case_when(
    type == "tc_a_acres_inside_forest" ~ "Forest",
    type == "tc_a_acres_outside_forest" ~ "Tree Canopy Outside Forest")) %>% 
  mutate(county = as.factor(county))

# Plot
#---------------------------------------
county_in_out_plot <- ggplot(data = county_in_out, aes(x = fct_rev(county), y = acres))+
  geom_col(aes(fill = type), position = "dodge") +
  scale_fill_manual(values = c("#24693d", "#6eb663")) +
  scale_y_continuous(breaks = c(0, 50000, 100000, 150000),
                     labels = c("0", "50,000", "100,000", "150,000")) +
  labs(title = "2018 Tree Canopy Inside and Outside Forests",
       x = "Jurisdiction",
       y = "Tree Canopy Area (Acres)") +
  coord_flip() +
  theme_minimal() +
  theme(
    text = element_text(family = "Times", size = 12),
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.title = element_blank(),
    legend.position = "bottom"
  )

county_in_out_plot

ggsave(here("Graphics", "1a_county_in_out_forest_2018.jpg"), county_in_out_plot, width = 7, height = 4.5)

# Stack Plot for Susan
#---------------------------------------
county_in_out_stack <- ggplot(data = county_in_out, aes(x = fct_rev(county), y = acres))+
  geom_col(aes(fill = type)) +
  scale_fill_manual(values = c("#24693d", "#6eb663")) +
  scale_y_continuous(breaks = c(0, 100000, 200000, 300000),
                     labels = c("0", "100,000", "200,000", "300,000")) +
  labs(title = "2018 Tree Canopy Inside and Outside Forests",
       x = "Jurisdiction",
       y = "Tree Canopy Area (Acres)") +
  coord_flip() +
  theme_minimal() +
  theme(
    text = element_text(family = "Times", size = 12),
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.title = element_blank(),
    legend.position = "bottom"
  )

county_in_out_stack

ggsave(here("Graphics", "1a_county_in_out_stack.jpg"), county_in_out_stack, width = 7, height = 4.5)

```
Tree Canopy Percent
```{r}
#---------------------------------------
# 2018 Percent Tree Canopy by County
#---------------------------------------
county_clean <- county_forest

county_clean[county_clean == c(" ", 0)] <- NA

county_canopy_percent <- county_clean %>% 
  select(county, can_p) %>% 
  mutate(county = as.factor(county)) %>% 
  drop_na()

# Percent Calculated for Labels
county_canopy_pecent_calc <- county_clean %>% 
  select(county, total_a_acres, can_a_acres) %>% 
  mutate(p_calc = can_a_acres/total_a_acres) %>% 
  mutate(county = as.factor(county)) %>% 
  drop_na()

# Plot
#---------------------------------------
county_canopy_plot <- ggplot(data = county_canopy_percent, aes(x = fct_rev(county), y = can_p)) +
  geom_col(aes(fill = county)) +
  geom_text(aes(label = round(can_p, digits = 1),
                color = county,
                hjust = -0.1),
            size = 3) +
  scale_fill_manual(values = county_pallette) +
  scale_color_manual(values = county_pallette) +
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  labs(
    title = "Percent Tree Canopy 2018",
    x = "Jurisdiction",
    y = "Percent Tree Canopy"
  ) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

county_canopy_plot

ggsave(here("Graphics", "1a_county_canopy.jpg"), county_canopy_plot)

# With Percent Labels
county_canopy_plot <- ggplot(data = county_canopy_pecent_calc, aes(x = fct_rev(county), y = p_calc)) +
  geom_col(aes(fill = county)) +
  geom_text(aes(label = percent(p_calc, accuracy = 1),
                color = county,
                hjust = -0.1),
            size = 3) +
  scale_fill_manual(values = county_pallette) +
  scale_color_manual(values = county_pallette) +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  labs(
    title = "Percent Tree Canopy 2018",
    x = "Jurisdiction",
    y = "Percent Tree Canopy"
  ) +
  coord_flip(clip = "off") +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

county_canopy_plot

ggsave(here("Graphics", "1a_county_canopy_lab.jpg"), county_canopy_plot)

```
Ordered Percent Canopy Plot
```{r}
#---------------------------------------
# Ordered by Percent
#---------------------------------------
county_ordered_p <- county_forest %>% 
  mutate(p_calc = can_a_acres/total_a_acres) %>% 
  select(county, land_a_acres, can_p, p_calc, x2020_pop) %>% 
  mutate(county = as.factor(county)) %>% 
  mutate(county = fct_reorder(county, desc(p_calc)))

# Plot
#---------------------------------------
ordered_p <- ggplot(data = county_ordered_p, aes(x = county, y = p_calc)) +
  geom_col(aes(fill = county)) +
  geom_text(aes(label = percent(p_calc, accuracy = 1),
                color = county,
                hjust = -0.1),
            size = 3) +
  scale_fill_manual(values = county_pallette) +
  scale_color_manual(values = county_pallette) +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  labs(
    title = "Percent Tree Canopy 2018",
    x = "Jurisdiction",
    y = "Percent Tree Canopy"
  ) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

ordered_p 

# ggsave(here("Graphics", "1a_county_ordered_p.jpg"), ordered_p)

#---------------------------------------
# Ordered by County Size
#---------------------------------------
county_ordered_size <- county_forest %>% 
  mutate(p_calc = can_a_acres/total_a_acres) %>% 
  select(county, land_a_acres, can_p, p_calc, x2020_pop) %>% 
  mutate(county = as.factor(county)) %>% 
  mutate(county = fct_reorder(county, desc(land_a_acres)))

# Plot
#---------------------------------------
ordered_size <- ggplot(data = county_ordered_size, aes(x = county, y = p_calc)) +
  geom_col(aes(fill = county)) +
  geom_text(aes(label = percent(p_calc, accuracy = 1),
                color = county,
                hjust = -0.1),
            size = 3) +
  scale_fill_manual(values = county_pallette) +
  scale_color_manual(values = county_pallette) +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  labs(
    title = "Percent Tree Canopy 2018 Ordered by Jurisdiction \n Size (Smallest Area to Largest Area)",
    x = "Jurisdiction",
    y = "Percent Tree Canopy"
  ) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

ordered_size

ggsave(here("Graphics", "1a_county_ordered_size.jpg"), ordered_size)

#---------------------------------------
# Ordered by Population
#---------------------------------------
county_ordered_pop <- county_forest %>% 
  mutate(p_calc = can_a_acres/total_a_acres) %>% 
  select(county, land_a_acres, can_p, p_calc, x2020_pop) %>% 
  mutate(county = as.factor(county)) %>% 
  mutate(county = fct_reorder(county, desc(x2020_pop)))

# Plot
#---------------------------------------
ordered_pop <- ggplot(data = county_ordered_pop, aes(x = fct_rev(county), y = p_calc)) +
  geom_col(aes(fill = county)) +
  geom_text(aes(label = percent(p_calc, accuracy = 1),
                color = county,
                hjust = -0.1),
            size = 3) +
  scale_fill_manual(values = county_pallette) +
  scale_color_manual(values = county_pallette) +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  labs(
    title = "Percent Tree Canopy 2018 Ordered by Jurisdiction \n Population (Smallest to Largest)",
    x = "Jurisdiction",
    y = "Percent Tree Canopy"
  ) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

ordered_pop 


# ggsave(here("Graphics", "1a_county_ordered_pop.jpg"), ordered_pop)

#---------------------------------------
# Ordered by population, stacked by inside vs. outside forest
#---------------------------------------
county_pop_stack <- county_forest %>% 
  mutate(p_calc_in = tc_a_acres_inside_forest/land_a_acres) %>%
  mutate(p_calc_out = tc_a_acres_outside_forest/land_a_acres) %>% 
  select(county, p_calc_in, p_calc_out, x2020_pop) %>% 
  pivot_longer(!c(county, x2020_pop), names_to = "type", values_to = "percent") %>%
      mutate(type = case_when(
    type == "p_calc_in" ~ "Inside Forest",
    type == "p_calc_out" ~ "Outside Forest")) %>% 
  mutate(type = as.factor(type)) %>% 
  mutate(county = as.factor(county)) %>% 
  mutate(county = fct_reorder(county, desc(x2020_pop)))

# Plot
#---------------------------------------
ordered_pop_stack <- ggplot(data = county_pop_stack, aes(x = fct_rev(county), y = percent)) +
  geom_bar(stat = "identity", position = position_stack(reverse = TRUE), aes(fill = type)) + # identityto make geom_bar work, position to switch stack
  scale_fill_manual(values = c("#24693d", "#6eb663")) +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  labs(title = "Percent Tree Canopy Cover by Jurisdiction \n Sorted by Population (Highest to Lowest)",
       x = "Jurisdiction",
       y = "Percent Tree Canopy Cover") +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0), size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

ordered_pop_stack

# ggsave(here("Graphics", "1a_county_ordered_pop_stack.jpg"), ordered_pop_stack)

```

Other land use change by county
```{r}
#---------------------------------------
# 2018 statewide land cover change by county
#---------------------------------------

county_lc_2018 <- county_forest %>% 
  select(county, can_p:shrub_p) %>% 
  pivot_longer(!county, names_to = "type", values_to = "percent") %>% 
    mutate(type = case_when(
    type == "can_p" ~ "Tree Canopy",
    type == "low_veg_p" ~ "Low Vegetation",
    type == "barren_p" ~ "Barren",
    type == "water_p" ~ "Water",
    type == "build_p" ~ "Building",
    type == "road_p" ~ "Road",
    type == "imperv_p" ~ "Impervious",
    type == "wetlands_p" ~ "Wetlands",
    type == "shrub_p" ~ "Shrub")) %>% 
  mutate(county = as.factor(county)) %>% 
  mutate(type = fct_reorder(type, desc(percent)))

county_lc_percent_stack <- ggplot(data = county_lc_2018, aes(fill = type, x = fct_rev(county), y = percent)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(
    title = "2018 Land Cover Proportions by County",
    x = "County",
    y = "Percent Land Cover") +
  scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1),
                     labels = c("0%", "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%")) +
  scale_fill_manual(values = lc_county_pallette) +
  coord_flip() +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.title = element_text(size = 14),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )+
  guides(fill = guide_legend(title = "Land Cover Type"))

county_lc_percent_stack

ggsave(here("Graphics", "1a_county_lc_stack.jpg"), county_lc_percent_stack)

```
Attempt merge state row into county plot
```{r}

# Merge Dataframes
state_merge <- state_lc_percent %>% 
  mutate(type = lc) %>% 
  select(type, percent) %>% 
  mutate(percent = percent*100)
  
state_merge$county <- c("Statewide")

state_merge <- state_merge[,c("county", "type", "percent")]

state_county_merge <- rbind(state_merge, county_lc_2018) %>% 
  mutate(county = as.factor(county)) %>%  
  mutate(county = fct_relevel(county, "Statewide", " "))

# Make bold label for state
# bold.state <- "Statewide"
# bold.label <- ifelse(levels(state_county_merge$county) %in% bold.state, yes = "bold", no = "plain")
# Almost works

# Plot
county_state_merge_plot <- ggplot(data = state_county_merge, aes(fill = type, x = fct_rev(county), y = percent)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(
    title = "2018 Land Cover Proportions by Jurisdiction",
    x = "Jurisdiction",
    y = "Percent Cover") +
  scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1),
                     labels = c("0%", "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%")) +
  scale_fill_manual(values = lc_county_pallette) +
  coord_flip() +
  theme_minimal() +
  theme(
#    axis.text.y = element_text(face = bold.label),
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.title = element_text(size = 14),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )+
  guides(fill = guide_legend(title = "Land Cover Type"))

county_state_merge_plot

ggsave(here("Graphics", "1a_county_state_lu_change.jpg"), county_state_merge_plot)

```


### Task 1b. Plantable Area
```{r}

#---------------------------------------
# Plantable Area by county (Acres)
#---------------------------------------

plantable_county_plot <- ggplot(data = plantable_county, aes(x = fct_rev(county), y = area_acres)) +
  geom_col(aes(fill = county)) +
  labs(x = "Jurisdiction", 
       y = "Total Area (Acres)",
       title = "Plantable Area by Jurisdiction 2018") +
  scale_fill_manual(values = county_pallette) +
  scale_y_continuous(breaks = c(0, 25000, 50000, 75000),
                     labels = c("0", "25,000", "50,000", "75,000")) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position = "none",
    text = element_text(family = "Times"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14, family = "Times", face = "bold"),
    plot.title = element_text(size = 16, family = "Times", face = "bold")
    )

plantable_county_plot

ggsave(here("Graphics", "1b_plantable_county.jpg"), plantable_county_plot, height = 4.5, width = 7)

```

```{r}
#---------------------------------------
# Plantable Area by county (Percent)
#---------------------------------------

# Calculate percent so labels will have % symbol
plantable_percent_calc <- plantable_percent %>% 
  select(county, area_acres, land_area_acres) %>% 
  mutate(p_land = area_acres/land_area_acres)

# Plot
plantable_percent_plot <- ggplot(data = plantable_percent_calc, 
                                 aes(x = fct_rev(county), y = p_land)) +
  geom_col(aes(fill = county)) +
  scale_fill_manual(values = county_pallette) +
  geom_text(aes(label =  percent(p_land, accuracy = 1),
                color = county,
                hjust = -0.1),
            size = 3) +
  scale_color_manual(values = county_pallette) +
  labs(title = "Percent Plantable Area by Jurisdiction 2018",
       x = "Jurisdiction",
       y = "Percent of Land Area") +
  scale_y_continuous(breaks = c(0, 0.05, 0.1, 0.15, 0.2, 0.25),
                     labels = c("0%", "5%", "10%", "15%", "20%", "25%")) +
  coord_flip(clip = "off") +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0), size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )
  
plantable_percent_plot

ggsave(here("Graphics", "plantable_percent_lab.jpg"), plantable_percent_plot)

```
Plantable stack by land cover
```{r}

plantable_stack_percent <- plantable_stack %>% 
  mutate(shrub_p = shrub_a_acres/land_area_acres) %>% 
  mutate(low_veg_p = low_veg_a_acres/land_area_acres) %>% 
  mutate(barren_p = barren_a_acres/land_area_acres) %>% 
  select(i_county, shrub_p, low_veg_p, barren_p) %>% 
  pivot_longer(!i_county, names_to = "lc", values_to = "percent_plantable") %>% 
  mutate(i_county = as.factor(i_county)) %>% 
  mutate(lc = fct_reorder(lc, desc(percent_plantable)))

ggplot(data = plantable_stack_percent, aes(x = fct_rev(i_county), y = percent_plantable)) +
         geom_col(aes(fill = lc)) +
  geom_text(aes(label = percent(percent_plantable, accuracy = 1),
                hjust = -0.1),
  size = 3) +
  scale_fill_manual(values = plantable_pallete) +
  coord_flip() +
  theme_minimal()

# ggsave(here("Graphics", "plantable_stack.jpg"))

emma_stack <- plantable_stack %>% 
  select(i_county, p_area, p_lc_area) %>% 
  pivot_longer(!i_county, names_to = "type", values_to = "percent") %>% 
  mutate(i_county = as.factor(i_county))

ggplot(data = emma_stack, aes(x = fct_rev(i_county), y = percent)) +
  geom_col(aes(fill = type), position = "dodge") +
  coord_flip() +
  theme_minimal()

ggsave(here("Graphics", "plantable_stack.jpg"))
  
```

Dummy Data Stack
```{r}
#---------------------------------------
# Prepare dummy data for stack plot of total potential area and plantable area after exclusion
#---------------------------------------
# Plantable are for all counties except hartford taken from old dataset
# Potential plantable area created using random number generator to make percent of total land between 35 and 70%

dummy_percent_stack <- dummy_data %>% 
  mutate(lc_a = lc_class_5_6*0.000247105) %>% # Convert LC to acres
  mutate(lc_p = lc_a/land_area) %>% # Get LC percent of total land
  mutate(lulc_a = plantable_area_lulc*0.000247105) %>% # Convert LULC to acres
  mutate(lulc_p = lulc_a/land_area) %>% 
  mutate(plantable_a = plantable*0.000247105) %>% # Convert plantable to acres
  mutate(plantable_p = plantable_a/land_area) %>%  # Get percent plantable of total land
  mutate(lc_stack = lc_p - lulc_p - plantable_p) %>%  # Subtract exclusion area from total so stack = total
  mutate(lulc_stack = lulc_p - plantable_p) %>% 
  select(i_county, plantable_p, lulc_stack, lc_stack) %>% 
  pivot_longer(!i_county, names_to = "type", values_to = "percent") %>% 
  mutate(type = case_when(
    type == "lc_stack" ~ "LC",
    type == "lulc_stack" ~ "LU/LC",
    type == "plantable_p" ~ "Plantable Area")) %>% 
  mutate(type = as.factor(type)) %>% 
  mutate(type = fct_relevel(type, "Land Cover", "Land Use and Land Cover", "Plantable Area")) %>% 
  mutate(i_county = as.factor(i_county))

# Plot Dummy Plantable Stack Plot
#---------------------------------------
ggplot(data = dummy_percent_stack, aes(x = fct_rev(i_county), y = percent)) +
  geom_col(aes(fill = type)) +
  scale_fill_manual(values = c("#85D5A3", # Lightest Green
                               "#3EB66A", # Lighter Green
                               "#24693d")) + # Dark Green
                               
  coord_flip() +
  theme_minimal() +
  labs(
    title = "Percent Potential Plantable Land with and without \n Exclusion Areas (Dummy Data)",
    x = "Jurisdiction",
    y = "Percent of Jurisdiction Land Area"
  ) +
    scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6),
                     labels = c("0%", "20%", "40%", "60%")) +
    theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0), size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

# ggsave(here("Graphics", "1b_plantable_dummy.jpg"))


```

