---
title: "Task 5: Tabulated Forest Cover/Change"
author: "Marie Bouffard"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# Attach packages
library(tidyverse)
library(readxl)
library(janitor)
library(here)

# Read in State data
state_tab <- read_excel(here("Data", "tabulated_forest.xlsx"), sheet = "state")

# Read in County data
county_tab <- read_excel(here("Data","tabulated_forest.xlsx"), sheet = "county")

# Read in Land Use data
land_use <- read.csv(here("Data", "5_LandUse.csv")) %>% 
  clean_names()

# Set Blanks to NA
  land_use[land_use == ""] <- NA

# Categorical County Color Pallette
county_pallette <- c("#68affc", "#485172", "#d6a7f0", "#7c46a0", "#20d8fd", "#155126", "#a2e84f", "#528f7a", "#7dd9a0", "#39970e", "#d0d9ae", "#e27040", "#f29180", "#e13224", "#922d4c", "#d9c937", "#fa217f", "#36f459", "#b825af", "#f27ff5", "#fda547", "#b7358d", "#a1e8af", "#7e52a0")

lu_pallette <- c("#F9DB6D", # Barren, light yellow
                 "#D9682A", # Buildings, brick
                 "#24693d", # Forest, green
                 "#F08701", # Impervious, orange 
                 "#8DBE87", # Low veg, light green
                 "#F9A620", # Roads, light orange
                 "#57AF94", # Shrub, green-blue
                 "#6eb663", # Outside Forest, light green
                 "#4059AD", # Water, royal blue
                 "#21A0A0") # Blue-green

# County Pallet
county_pallette <- c("#68affc", "#485172", "#d6a7f0", "#7c46a0", "#20d8fd", "#155126", "#a2e84f", "#528f7a", "#7dd9a0", "#39970e", "#d0d9ae", "#e27040", "#f29180", "#e13224", "#922d4c", "#d9c937", "#fa217f", "#36f459", "#b825af", "#f27ff5", "#fda547", "#b7358d", "#a1e8af", "#7e52a0")

# Use stringr::str_wrap() to create breaks in long facet titles
stwr <- function(string, nwrap = 15){
  paste(strwrap(string, width = nwrap), collapse = "\n")
}

stwr = Vectorize(stwr)

```
### Forested Area at the State Level
```{r}
#---------------------------------------
# Maryland Statewide Tabulated Forest Cover
#---------------------------------------

# Wrangle state data (get rid of non-forested, convert to acres)
state_clean <- state_tab %>% 
  clean_names() %>% 
  filter(reclassified_value == "1") %>%
  select(year:area_m, -reclassified_value) %>% 
  mutate(acres = area_m*0.000247105)

# Plot totals over time
plot_totals_state <- ggplot(data = state_clean, aes(x = year, y = acres))+
  geom_line(color = "seagreen4", size = 2)+
    labs(x = "Year",
       y = "Acres of Forest") +
    scale_y_continuous(breaks = c(3300000, 3325000, 3350000),
    labels = c("3,300,000","3,325,000","3,350,000"))+
  theme_minimal() +
  theme(text = element_text(size = 14, family = "Times"),
        axis.title = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))

# ggsave(here("Graphics", "totals_state.jpg"),plot_totals_state)

plot_totals_state

```
Change between Time periods
```{r}
# State change between time periods
#---------------------------------------
state_change <- state_clean %>% 
  mutate(year_diff = acres - lead(acres))

# Plot difference between time periods
plot_change_state <- ggplot(data = state_change, aes(x = year, y = year_diff))+
  geom_col(fill = "seagreen4")+
  scale_x_continuous(breaks = c(2005, 2010, 2015, 2020),
    labels = c("2000-2005","2005-2010","2010-2015","2015-2020"))+
    scale_y_continuous(breaks = c(0, 10000, 20000),
    labels = c("0","10,000","20,000"))+
    labs(x = "Time Period",
       y = "Change in Total Acreage") +
  # scale_y_continuous(limits=c(-30000,1000))+
  # geom_hline(aes(yintercept=0))+
  #   geom_vline(aes(xintercept=1997))+
  theme_minimal()+
  theme(text = element_text(size = 16, family = "Times"),
        axis.title = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))

plot_change_state

# ggsave(here("Graphics", "change_state.jpg"),plot_change_state)

```


### Forested Area at the County Level
```{r}
#---------------------------------------
# Tabulated Forest Cover by county
#---------------------------------------

# Wrangle county data (convert to tidy format, convert to acres)
county_clean <- county_tab %>% 
  filter(Value == 1) %>%
  select("COUNTY":"2020", -Value) %>% 
  pivot_longer(!COUNTY, names_to = "year", values_to = "area_m") %>% 
  mutate(acres = area_m*0.000247105) %>% 
  mutate(year = as.numeric(year)) %>%
  clean_names()

# Plot totals over time by county
plot_totals_county_all <- ggplot(data = county_clean, aes(x = year, y = acres)) +
  geom_line(color = "seagreen4", size = 1) +
  scale_x_continuous(breaks = c(2000, 2005, 2010, 2015, 2020), 
                     labels = c("2000","", "2010","","2020")) +
  facet_wrap(~county, ncol = 4, scales = "free_y") +
      labs(x = "Year",
       y = "Forested Area (acres)") +
  theme_minimal() +
  theme(text = element_text(family = "Times", size = 10),
    axis.title = element_text(size = 16, family = "Times"),
    axis.text = element_text(size = 10, family = "Times"),
    panel.spacing.x = unit(2, "lines"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0), size = 14, face = "bold"))

# ggsave(here("Graphics", "totals_county_all.jpg"),plot_totals_county_all, width=7, height=7)

plot_totals_county_all

# Plot totals over time by county with county pallette
plot_totals_county_cp <- ggplot(data = county_clean, aes(x = year, y = acres)) +
  geom_line(aes(color = county), size = 1) +
  scale_color_manual(values = county_pallette) +
  scale_x_continuous(breaks = c(2000, 2005, 2010, 2015, 2020), 
                     labels = c("2000","", "2010","","2020")) +
  facet_wrap(~county, ncol = 4, scales = "free_y") +
      labs(x = "Year",
       y = "Forested Area (acres)") +
  theme_minimal() +
  theme(text = element_text(family = "Times", size = 10),
    axis.title = element_text(size = 16, family = "Times"),
    axis.text = element_text(size = 10, family = "Times"),
    panel.spacing.x = unit(2, "lines"),
    legend.position = "none",
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0), size = 14, face = "bold"))

# ggsave(here("Graphics", "totals_county_all_cp.jpg"),plot_totals_county_cp, width=7, height=7)

plot_totals_county_cp

```
Change by time periods faceted by county
```{r}
# County change between time periods
#---------------------------------------
county_change <- county_clean %>% 
  group_by(county) %>% 
  mutate(year_diff = acres - lag(acres))

# Plot difference between time periods
plot_change_county_all <- ggplot(data = county_change, aes(x = year, y = year_diff))+
  geom_col(fill = "seagreen4")+
  scale_x_continuous(breaks = c(2005, 2010, 2015, 2020),
    labels = c("2000-2005","2005-2010","2010-2015","2015-2020"))+
    labs(x = "Time Period",
       y = "Total Change in Acreage") +
    geom_hline(aes(yintercept=0))+
    geom_vline(aes(xintercept=2002))+
  facet_wrap(~county, ncol = 4, scales = "free_y")+
  theme_minimal() +
  theme(
    text = element_text(family = "Times"),
    axis.title = element_text(size = 16, family = "Times"),
    axis.text = element_text(size = 10, family = "Times"),
    axis.text.x = element_text(angle = 90),
    panel.spacing = unit(1, "lines"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0), size = 14, face = "bold")
    )

# ggsave(here("Graphics", "change_county_all.jpg"),plot_change_county_all, width=7, height=7)

plot_change_county_all

# Plot difference between time periods with county pallette
plot_change_county_cp <- ggplot(data = county_change, aes(x = year, y = year_diff))+
  geom_col(aes(fill = county))+
  scale_fill_manual(values = county_pallette) +
  scale_x_continuous(breaks = c(2005, 2010, 2015, 2020),
    labels = c("2000-2005","2005-2010","2010-2015","2015-2020"))+
    labs(x = "Time Period",
       y = "Total Change in Acreage") +
    geom_hline(aes(yintercept=0))+
    geom_vline(aes(xintercept=2002))+
  facet_wrap(~county, ncol = 4, scales = "free_y")+
  theme_minimal() +
  theme(
    text = element_text(family = "Times"),
    axis.title = element_text(size = 16, family = "Times"),
    axis.text = element_text(size = 10, family = "Times"),
    axis.text.x = element_text(angle = 90),
    panel.spacing = unit(1, "lines"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0), size = 14, face = "bold"),
    legend.position = "none"
    )

# ggsave(here("Graphics", "change_county_cp.jpg"),plot_change_county_cp, width=7, height=7)

plot_change_county_cp

```

Change by time periods faceted by time period

```{r}
# Try faceting by time period instead of county
#---------------------------------------

# Wrangle for time period categories

county_change_period <- county_change %>%
  filter(year %in% c(2005,2010,2015,2020)) %>% 
  mutate(time_period = case_when(
    year == 2005 ~ "2000 - 2005",
    year == 2010 ~ "2005 - 2010",
    year == 2015 ~ "2010 - 2015",
    year == 2020 ~ "2015 - 2020"
  ))

#Trying to rename years to time periods
# period_names <- list(
#   "2005"="2000-2005",
#   "2010"="2005-2010",
#   "2015"="2010-2015",
#   "2020"="2015-2020")
# 
# period_labeller <- function(year,value){
#   return(period_names[value])
# }

county_change_by_period <- ggplot(data = county_change_period, aes(x = county, y = year_diff))+
  geom_col(aes(fill = county)) +
  scale_fill_manual(values = county_pallette) +
  facet_wrap(~time_period)+
  labs(x = "County",
       y = "Total Change in Acreage")+
  theme_minimal()+
  geom_hline(aes(yintercept=0))+
  geom_vline(aes(xintercept=0))+
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_blank()
  ) +
  guides(fill = guide_legend(nrow = 4))

county_change_by_period

# ggsave(here("Graphics", "county_change_by_period.jpg"), county_change_by_period)

```

### Land Use

Acres
```{r}
#---------------------------------------
# Land Use Change in Acres
#---------------------------------------
land_use_acres <- land_use %>% 
  select(i_desclu, low_veg_change_acres:outside_forest_change_acres) %>% 
  pivot_longer(!i_desclu, names_to = "land_use", values_to = "acres") %>% 
  drop_na() %>% 
    mutate(land_use = case_when(
    land_use == "low_veg_change_acres" ~ "Low Vegetation",
    land_use == "barren_change_acres" ~ "Barren",
    land_use == "water_change_acres" ~ "Water",
    land_use == "buildings_change_acres" ~ "Buildings",
    land_use == "road_change_acres" ~ "Roads",
    land_use == "shrub_change_acres" ~ "Shrub",
    land_use == "wetlands_change_acres" ~ "Wetland",
    land_use == "impervious_change_acres" ~ "Impervious",
    land_use == "forest_change_acres" ~ "Forest",
    land_use == "outside_forest_change_acres" ~ "Tree Canopy Outside Forest"))

# String Wrap Function
land_use_acres$i_desclu = stwr(land_use_acres$i_desclu)

lu_acres_plot <- ggplot(data = land_use_acres, aes(x = land_use, y = acres)) +
  geom_col(aes(fill = land_use)) +
  facet_wrap(~i_desclu, scales = "free_y") +
  labs(title = "Land Use Change",
       y = "Change in Acreage") +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
  scale_fill_manual(values = lu_pallette) +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    text = element_text(family = "Times", size = 14),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold"),
#    legend.position = "none",
    legend.position = "bottom",
    legend.title = element_text(size = 14, face = "bold"),
    legend.title.align = 0.5,
     strip.background = element_rect(color = "grey40", fill = "grey30"),
    strip.text = element_text(size = 12, color = "white", face = "bold"),
    panel.border = element_rect(color = "grey40", fill = NA)
   ) +
    guides(fill = guide_legend(title = "Land Use",
                               title.position = "top",
                               nrow = 2))
lu_acres_plot

# ggsave(here("Graphics", "5_land_use_change_legend.jpg"), lu_acres_plot, width=9, height=7)

```

```{r}

county_change_by_period_v2 <- ggplot(data = county_change_period, aes(x = county, y = year_diff))+
  geom_col(aes(fill = county))+
  facet_wrap(~time_period) +
  scale_fill_manual(values = county_pallette) +
  labs(x = " ",
       y = "Total Change in Acreage")+
  theme_minimal()+
  geom_hline(aes(yintercept=0))+
  geom_vline(aes(xintercept=0))+
  theme(
    axis.text.x = element_blank(),
    axis.title.y = element_text(size = 14, face = "bold"),
    strip.background = element_rect(color = "grey40", fill = "grey30"),
    strip.text = element_text(size = 14, color = "white", face = "bold"),
    panel.border = element_rect(color = "grey40", fill = NA),
#    legend.position = "none"
    legend.position = "bottom",
    legend.title = element_text(size = 14, face = "bold"),
    legend.title.align = 0.5,
  ) +
  guides(fill = guide_legend(title = "County",
                             title.position = "top",
                             nrow = 4))
# )
county_change_by_period_v2

# ggsave(here("Graphics", "county_change_by_period_v2.jpg"), county_change_by_period_v2)

# County Change by Period With Lables for Jarlath
# county_change_demo <- ggplot(data = county_change_period, aes(x = county, y = year_diff))+
#   geom_col(aes(fill = county))+
#   geom_text(aes(label = county, color = county), check_overlap = TRUE, angle = 45, size = 3.5) +
#   facet_wrap(~time_period) +
#   scale_fill_manual(values = county_pallette) +
#   scale_color_manual(values = county_pallette) +
#   labs(x = " ",
#        y = "Total Change in Acreage")+
#   theme_minimal()+
#   geom_hline(aes(yintercept=0))+
#   geom_vline(aes(xintercept=0))+
#   theme(
#     axis.text.x = element_blank(),
#     axis.title.y = element_text(size = 14, face = "bold"),
#     strip.background = element_rect(color = "grey40", fill = "grey30"),
#     strip.text = element_text(size = 14, color = "white", face = "bold"),
#     panel.border = element_rect(color = "grey40", fill = NA),
#     legend.position = "none"
#   )

# ggsave(here("Graphics", "county_change_labled.jpg"), county_change_demo)

```

### Counties Individually (Just in case)
Allegany County
```{r}

# Allegany
#---------------------------------------
allegany <- county_change %>% 
  filter(county == "Allegany")

allegany_total <- ggplot(data = allegany, aes(x = year, y = acres)) +
  geom_line(color = "seagreen4", size = 2) +
      labs(x = "Year",
       y = "Forested Area (acres)",
       title = "Allegany County") +
  theme_minimal()

allegany_total

allegany_change <- ggplot(data = allegany, aes(x = year, y = year_diff))+
  geom_col(fill = "seagreen4")+
  scale_x_continuous(breaks = c(2005, 2010, 2015, 2020),
    labels = c("2000-2005","2005-2010","2010-2015","2015-2020"))+
    labs(x = "Time Period",
       y = "Change in Total Acreage",
       title = "Allegany County") +
  geom_hline(aes(yintercept=0))+
    geom_vline(aes(xintercept=2002))+
  theme_minimal()

allegany_change

```
Anne Arundel County
```{r}
# Anne Arundel
#---------------------------------------
anne_arundel <- county_change %>% 
  filter(county == "Anne Arundel")

anne_arundel_total <- ggplot(data = anne_arundel, aes(x = year, y = acres)) +
  geom_line(color = "seagreen4", size = 2) +
      labs(x = "Year",
       y = "Forested Area (acres)",
       title = "Anne Arundel County") +
  theme_minimal()

anne_arundel_total

anne_arundel_change <- ggplot(data = anne_arundel, aes(x = year, y = year_diff))+
  geom_col(fill = "seagreen4")+
  scale_x_continuous(breaks = c(2005, 2010, 2015, 2020),
    labels = c("2000-2005","2005-2010","2010-2015","2015-2020"))+
    labs(x = "Time Period",
       y = "Change in Total Acreage",
       title = "Anne Arundel County") +
  geom_hline(aes(yintercept=0))+
    geom_vline(aes(xintercept=2002))+
  theme_minimal()

anne_arundel_change

```
Baltimore County
```{r}
# Baltimore
#---------------------------------------
baltimore <- county_change %>% 
  filter(county == "Baltimore")

baltimore_total <- ggplot(data = baltimore, aes(x = year, y = acres)) +
  geom_line(color = "seagreen4", size = 2) +
      labs(x = "Year",
       y = "Forested Area (acres)",
       title = "Baltimore County") +
  theme_minimal()

baltimore_total

baltimore_change <- ggplot(data = baltimore, aes(x = year, y = year_diff))+
  geom_col(fill = "seagreen4")+
  scale_x_continuous(breaks = c(2005, 2010, 2015, 2020),
    labels = c("2000-2005","2005-2010","2010-2015","2015-2020"))+
    labs(x = "Time Period",
       y = "Change in Total Acreage",
       title = "Baltimore County") +
  geom_hline(aes(yintercept=0))+
    geom_vline(aes(xintercept=2002))+
  theme_minimal()

baltimore_change

```
Baltimore City County
```{r}
# Baltimore City
#---------------------------------------
baltimore_city <- county_change %>% 
  filter(county == "Baltimore City")

baltimore_city_total <- ggplot(data = baltimore_city, aes(x = year, y = acres)) +
  geom_line(color = "seagreen4", size = 2) +
      labs(x = "Year",
       y = "Forested Area (acres)",
       title = "Baltimore City County") +
  theme_minimal()

baltimore_city_total

baltimore_city_change <- ggplot(data = baltimore_city, aes(x = year, y = year_diff))+
  geom_col(fill = "seagreen4")+
  scale_x_continuous(breaks = c(2005, 2010, 2015, 2020),
    labels = c("2000-2005","2005-2010","2010-2015","2015-2020"))+
    labs(x = "Time Period",
       y = "Change in Total Acreage",
       title = "Baltimore City County") +
  geom_hline(aes(yintercept=0))+
    geom_vline(aes(xintercept=2002))+
  theme_minimal()

baltimore_city_change

```
Calvert County
```{r}
# Calvert
#---------------------------------------
calvert <- county_change %>% 
  filter(county == "Calvert")

calvert_total <- ggplot(data = calvert, aes(x = year, y = acres)) +
  geom_line(color = "seagreen4", size = 2) +
      labs(x = "Year",
       y = "Forested Area (acres)",
       title = "Calvert County") +
  theme_minimal()

calvert_total

calvert_change <- ggplot(data = calvert, aes(x = year, y = year_diff))+
  geom_col(fill = "seagreen4")+
  scale_x_continuous(breaks = c(2005, 2010, 2015, 2020),
    labels = c("2000-2005","2005-2010","2010-2015","2015-2020"))+
    labs(x = "Time Period",
       y = "Change in Total Acreage",
       title = "Calvert County") +
  geom_hline(aes(yintercept=0))+
    geom_vline(aes(xintercept=2002))+
  theme_minimal()

calvert_change

```
Caroline County
```{r}
# Caroline
#---------------------------------------
caroline <- county_change %>% 
  filter(county == "Caroline")

caroline_total <- ggplot(data = caroline, aes(x = year, y = acres)) +
  geom_line(color = "seagreen4", size = 2) +
      labs(x = "Year",
       y = "Forested Area (acres)",
       title = "Caroline County") +
  theme_minimal()

caroline_total

caroline_change <- ggplot(data = calvert, aes(x = year, y = year_diff))+
  geom_col(fill = "seagreen4")+
  scale_x_continuous(breaks = c(2005, 2010, 2015, 2020),
    labels = c("2000-2005","2005-2010","2010-2015","2015-2020"))+
    labs(x = "Time Period",
       y = "Change in Total Acreage",
       title = "Caroline County") +
  geom_hline(aes(yintercept=0))+
    geom_vline(aes(xintercept=2002))+
  theme_minimal()

caroline_change

```
Carroll County
```{r}
# Carroll
#---------------------------------------
carroll <- county_change %>% 
  filter(county == "Carroll")

carroll_total <- ggplot(data = carroll, aes(x = year, y = acres)) +
  geom_line(color = "seagreen4", size = 2) +
      labs(x = "Year",
       y = "Forested Area (acres)",
       title = "Carroll County") +
  theme_minimal()

carroll_total

carroll_change <- ggplot(data = carroll, aes(x = year, y = year_diff))+
  geom_col(fill = "seagreen4")+
  scale_x_continuous(breaks = c(2005, 2010, 2015, 2020),
    labels = c("2000-2005","2005-2010","2010-2015","2015-2020"))+
    labs(x = "Time Period",
       y = "Change in Total Acreage",
       title = "Carroll County") +
  geom_hline(aes(yintercept=0))+
    geom_vline(aes(xintercept=2002))+
  theme_minimal()

carroll_change

```