---
title: "Task 2: Forest Health"
author: "Marie Bouffard"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# Attach packages
library(tidyverse)
library(here)
library(janitor)

# Read in State Fragmentation Data
state_frag <- read.csv(here("Data", "2_frag_statestats.csv")) %>% 
  clean_names()

# Read in County Fragmentation Data
county_frag <- read.csv(here("Data", "2_frag_countystats.csv")) %>% 
  clean_names()

# Fragmentation Color Scheme
frag_pallete <- c("#035339", # Large core, dark green
                  "#00734C", # Medium core, green
                  "#3B9E70", # Small core, lighter green
                  "#D4F0D1", # Edge, white-green
                  "#EE4266")  # Patches, pink 

frag_pallete2 <- c("#D4F0D1", # Edge, white-green 
                  "#00734C", # Medium core, green
                  "#035339", # Large core, dark green
                  "#EE4266", # Patches, pink 
                  "#3B9E70") # Small core, lighter green


frag_pallete_stack <- c("#D4F0D1", # Edge, white-green
                        "#EE4266", # Patches, pink
                        "#3B9E70", # Small core, lighter green
                        "#00734C", # Medium core, green
                        "#035339") # Large core, dark green

frag_pallete_stack_merge <- c("#D4F0D1", # Edge, white-green
                              "#EE4266", # Patches, pink
                        "#3B9E70", # Small core, lighter green
                        "#00734C", # Medium core, green
                        "#035339") # Large core, dark green

# Categorical County Color Pallette
county_pallette <- c("#68affc", "#485172", "#d6a7f0", "#7c46a0", "#20d8fd", "#155126", "#a2e84f", "#528f7a", "#7dd9a0", "#39970e", "#d0d9ae", "#e27040", "#f29180", "#e13224", "#922d4c", "#d9c937", "#fa217f", "#36f459", "#b825af", "#f27ff5", "#fda547", "#b7358d", "#a1e8af", "#7e52a0")
                         

```

### Forest Fragmentation
State 
```{r}
#---------------------------------------
# Fragmentation Metrics Change 2013-2018
#---------------------------------------
state_frag_change <- state_frag %>% 
  select(patch_change:lcore_change) %>% 
  pivot_longer(patch_change:lcore_change, names_to = "metric", values_to = "acres_change") %>% 
  mutate(metric = case_when(
    metric == "patch_change" ~ "Patch",
    metric == "edge_change" ~ "Edge",
    metric == "score_change" ~ "Small Core",
    metric == "mcore_change" ~ "Medium Core",
    metric == "lcore_change" ~ "Large Core")) %>% 
  mutate(metric = as.factor(metric)) %>% 
  mutate(metric = fct_relevel(metric,
                              "Large Core",
                              "Medium Core",
                              "Small Core",
                              "Edge",
                              "Patch"))
# Plot
#---------------------------------------
state_frag_plot <- ggplot(data = state_frag_change, aes(x = metric, y = acres_change)) +
  geom_col(fill = "seagreen4") +
  labs(x = "Forest Fragment Type", 
       y = "Total Area Change (Acres)",
       title = "Total Area Change 2013 to 2018") +
    scale_y_continuous(breaks = c(-15000, -10000, -5000, 0, 5000, 10000),
                     labels = c("-15,000", "-10,000", "-5,000", "0", "5,000", "10,000")) +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
    theme(
    text = element_text(family = "Times"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14, family = "Times", face = "bold"),
    plot.title = element_text(size = 16, family = "Times", face = "bold"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))
    )

state_frag_plot

ggsave(here("Graphics", "2_state_frag_change.jpg"), state_frag_plot)

# Color Coded
#---------------------------------------
state_frag_color_plot <- ggplot(data = state_frag_change, aes(x = metric, y = acres_change)) +
  geom_col(aes(fill = metric)) +
 # geom_text(aes(label = round(acres_change, digits = 0)),
 #           vjust = 1) +
    annotate("text", # Large Core
           x = 1, y = -2700,
           label = "-1,938", color = "#035339") +
  annotate("text", # Medium Core
           x = 2, y = -1300,
           label = "-482", color = "#00734C") +
  annotate("text", # Small Core
           x = 3, y = -8000,
           label = "-7,240", color = "#3B9E70") +
  annotate("text", # Edge
           x = 4, y = -16000,
           label = "-15,329", color = "#8CD784") +
    annotate("text", # Patch
           x = 5, y = 14300,
           label = "13,067", color = "#EE4266") +
  coord_cartesian(clip = "off") +
  scale_fill_manual(values = frag_pallete) +
  scale_color_manual(values = frag_pallete) +
  labs(x = "Forest Fragment Type", 
       y = "Total Area Change (Acres)",
       title = "Total Area Change 2013 to 2018") +
    scale_y_continuous(breaks = c(-15000, -10000, -5000, 0, 5000, 10000),
                     labels = c("-15,000", "-10,000", "-5,000", "0", "5,000", "10,000")) +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
    theme(
    text = element_text(family = "Times"),
    axis.text = element_text(size = 12),
    axis.title.y = element_text(size = 14, 
                                face = "bold", 
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    plot.title = element_text(size = 16, family = "Times", face = "bold"),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    legend.title = element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title.align = 0.5,
    ) +
  guides(fill = guide_legend(title = "Forest Fragment Type", 
                             title.position = "top"))

state_frag_color_plot

ggsave(here("Graphics", "2_state_frag_change_color.jpg"), state_frag_color_plot)

```
2018 Totals
```{r}

#---------------------------------------
# Fragmentation Totals 2018
#---------------------------------------

state_frag_2018 <- state_frag %>% 
  select(patch_acres_2018:lcore_acres_2018) %>% 
  pivot_longer(patch_acres_2018:lcore_acres_2018, names_to = "metric", values_to = "acres") %>% 
  mutate(metric = case_when(
    metric == "patch_acres_2018" ~ "Patch",
    metric == "edge_acres_2018" ~ "Edge",
    metric == "s_core_acres_2018" ~ "Small Core",
    metric == "m_core_acres_2018" ~ "Medium Core",
    metric == "lcore_acres_2018" ~ "Large Core")) %>% 
  mutate(metric = as.factor(metric)) %>% 
  mutate(metric = fct_relevel(metric,
                              "Large Core",
                              "Medium Core",
                              "Small Core",
                              "Edge",
                              "Patch"))
# Plot
#---------------------------------------
state_2018_plot <- ggplot(data = state_frag_2018, aes(x = metric, y = acres)) +
  geom_col(fill = "seagreen4") +
  labs(x = "Forest Fragment Type", 
       y = "Total Area (Acres)",
       title = "Forest Type 2018") +
  scale_y_continuous(breaks = c(300000, 600000, 900000),
                     labels = c("300,000", "600,000", "900,000")) +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
    theme(
    text = element_text(family = "Times"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14, family = "Times", face = "bold"),
    plot.title = element_text(size = 16, family = "Times", face = "bold"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))
    )

state_2018_plot

ggsave(here("Graphics", "2_state_frag_2018.jpg"), state_2018_plot)

# Color Coded
#---------------------------------------
state_2018_color_plot <- ggplot(data = state_frag_2018, aes(x = metric, y = acres)) +
  geom_col(aes(fill = metric)) +
  annotate("text", # Large Core
           x = 1, y = 120000,
           label = "66,810", color = "#035339") +
  annotate("text", # Medium Core
           x = 2, y = 85000,
           label = "35,411", color = "#00734C") +
  annotate("text", # Small Core
           x = 3, y = 210000,
           label = "106,246", color = "#3B9E70") +
  annotate("text", # Edge
           x = 4, y = 1150000,
           label = "1,102,331", color = "#8CD784") +
    annotate("text", # Patch
           x = 5, y = 360000,
           label = "310,392", color = "#EE4266") +
  # geom_text(aes(label = round(acres, digits = 2),
  #              color = metric),
  #          vjust = -0.3) +
  coord_cartesian(clip = "off") +
  scale_fill_manual(values = frag_pallete) +
  scale_color_manual(values = frag_pallete) +
  labs(x = "Forest Type", 
       y = "Total Area (Acres)",
       title = "Forest Type 2018") +
  scale_y_continuous(breaks = c(300000, 600000, 900000),
                     labels = c("300,000", "600,000", "900,000")) +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
    theme(
    text = element_text(family = "Times"),
    axis.text = element_text(size = 12),
    axis.title.y = element_text(size = 14, 
                                face = "bold", 
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    plot.title = element_text(size = 16, family = "Times", face = "bold"),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    legend.title = element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title.align = 0.5,
    ) +
  guides(fill = guide_legend(title = "Forest Fragment Type", 
                             title.position = "top"))

state_2018_color_plot

ggsave(here("Graphics", "2_state_frag_color_2018.jpg"), state_2018_color_plot)

```
2018 State Percent
```{r}

state_frag_2018_percent <- state_frag %>% 
  select(patch_acres_2018:lcore_acres_2018) %>% 
  pivot_longer(patch_acres_2018:lcore_acres_2018, names_to = "frag_type", values_to = "acres") %>% 
  mutate(frag_type = case_when(
    frag_type == "patch_acres_2018" ~ "Patch",
    frag_type == "edge_acres_2018" ~ "Edge",
    frag_type == "s_core_acres_2018" ~ "Small Core",
    frag_type == "m_core_acres_2018" ~ "Medium Core",
    frag_type == "lcore_acres_2018" ~ "Large Core")) %>% 
    mutate(percent = acres/sum(acres)*100
        # label = scales::percent(percent)
         )

```

2013 totals
```{r}

#---------------------------------------
# Fragmentation Totals 2013
#---------------------------------------

state_frag_2013 <- state_frag %>% 
  select(patch_acres_2013:lcore_acres_2013) %>% 
  pivot_longer(patch_acres_2013:lcore_acres_2013, names_to = "metric", values_to = "acres") %>% 
  mutate(metric = case_when(
    metric == "patch_acres_2013" ~ "Patch",
    metric == "edge_acres_2013" ~ "Edge",
    metric == "s_core_acres_2013" ~ "Small Core",
    metric == "m_core_acres_2013" ~ "Medium Core",
    metric == "lcore_acres_2013" ~ "Large Core")) %>% 
  mutate(metric = as.factor(metric)) %>% 
  mutate(metric = fct_relevel(metric,
                              "Large Core",
                              "Medium Core",
                              "Small Core",
                              "Edge",
                              "Patch"))

state_2013_plot <- ggplot(data = state_frag_2013, aes(x = metric, y = acres)) +
  geom_col(fill = "seagreen4") +
  labs(x = "Forest Type", 
       y = "Total Area (Acres)",
       title = "Forest Type 2013") +
  scale_y_continuous(breaks = c(300000, 600000, 900000),
                     labels = c("300,000", "600,000", "900,000")) +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
    theme(
    text = element_text(family = "Times"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14, family = "Times", face = "bold"),
    plot.title = element_text(size = 16, family = "Times", face = "bold"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))
    )

state_2013_plot

ggsave(here("Graphics", "2_state_frag_2013.jpg"), state_2013_plot)

```

State Frag 2013 and 2018 combined
```{r}

# Add year column to both dfs
state_frag_2018$year <- c("2018")

state_frag_2013$year <- c("2013")

# Merge and wrangle
state_frag_13_18 <- rbind(state_frag_2013, state_frag_2018)

# Plot
state_frag_merge_plot <- ggplot(data = state_frag_13_18, aes(x = metric, y = acres)) +
  geom_col(aes(fill = year), position = "dodge") +
  scale_fill_manual(values = c("#6eb663", "#24693d")) +
  labs(title = "Forest Fragment Type Area in 2013 and 2018",
       x = "Forest Fragment Type",
       y = "Total Area (Acres)") +
  scale_y_continuous(breaks = c(0, 300000, 600000, 900000),
                     labels = c("0", "300,000", "600,000", "900,000")) +
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 14, face = "bold", margin = margin(t = 0, r = 10, b = 0, l = 0)),
    legend.position = "bottom",
    legend.title.align = 0.5,
    legend.title = element_text(size = 14, face = "bold")
  ) +
  guides(fill = guide_legend(title = "Year", 
                             title.position = "top"))
ggsave(here("Graphics", "2_state_frag_merge.jpg"), state_frag_merge_plot)

```


County Change Acres
```{r}                                                               
#---------------------------------------
# Fragmentation Acres Change 2013-2018
#---------------------------------------
county_change <- county_frag %>% 
  select(county, patch_change:lcore_change) %>% 
  pivot_longer(!county, 
               names_to = "frag_type",
               values_to = "acres_change") %>% 
    mutate(frag_type = case_when(
    frag_type == "patch_change" ~ "Patch",
    frag_type == "edge_change" ~ "Edge",
    frag_type == "score_change" ~ "Small Core",
    frag_type == "mcore_change" ~ "Medium Core",
    frag_type == "lcore_change" ~ "Large Core")) %>% 
  mutate(frag_type = as.factor(frag_type)) %>% 
  mutate(frag_type = fct_relevel(frag_type,
                              "Large Core",
                              "Medium Core",
                              "Small Core",
                              "Edge",
                              "Patch"))
# Plot
#---------------------------------------

# Stacked
ggplot(county_change, aes(x = county, y = acres_change)) +
  geom_col(aes(fill = frag_type)) +
  scale_fill_manual(values = frag_pallete) +
  theme_minimal() +
  coord_flip()

# Facet by county
county_frag_acres <- ggplot(county_change, aes(x = frag_type, y = acres_change)) +
  geom_col(aes(fill = frag_type)) +
  scale_fill_manual(values = frag_pallete) +
  labs(title = "Forest Fragment Type Area Change \n from 2013 to 2018",
       y = "Area (acres)") +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
  facet_wrap(~county, scale = "free_y") +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    legend.title = element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title.align = 0.5,
    strip.background = element_rect(color = "grey40", fill = "grey30"),
    strip.text = element_text(size = 9, color = "white", face = "bold"),
    panel.border = element_rect(color = "grey40", fill = NA)
   ) +
    guides(fill = guide_legend(title = "Forest Fragment Type",
                               title.position = "top"))

county_frag_acres

ggsave(here("Graphics", "2_county_frag_change_acres.jpg"), county_frag_acres, height = 7)

# Facet by Frag Type
county_frag_facet_acres <- ggplot(county_change, aes(x = county, y = acres_change)) +
  geom_col(aes(fill = county)) +
  scale_fill_manual(values = county_pallette) +
  labs(title = "Forest Fragment Type Area Change \n from 2013 to 2018",
       y = "Area (acres)") +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
  facet_wrap(~frag_type, scale = "free_y") +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    legend.title = element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title.align = 0.5,
    strip.background = element_rect(color = "grey40", fill = "grey30"),
    strip.text = element_text(size = 12, color = "white", face = "bold"),
    panel.border = element_rect(color = "grey40", fill = NA)
   ) +
    guides(fill = guide_legend(title = "Jurisdiction",
                               title.position = "top",
                               nrow = 4))

county_frag_facet_acres

ggsave(here("Graphics", "2_county_fragtype_facet_change.jpg"), county_frag_facet_acres, height = 6)

```
County Change Percent
```{r}
#---------------------------------------
# Fragmentation Percent Change 2013-2018
#---------------------------------------

# Divide 2018 acres by 2013 acres
county_frag_percent <- county_frag %>% 
  select(county, patch_acres_2013:lcore_acres_2018) %>% 
  mutate(patch_change = patch_acres_2018/patch_acres_2013) %>% 
  mutate(edge_change = edge_acres_2018/edge_acres_2013) %>% 
  mutate(s_core_change = s_core_acres_2018/s_core_acres_2013) %>% 
  mutate(m_core_change = m_core_acres_2018/m_core_acres_2013) %>% 
  mutate(l_core_change = lcore_acres_2018/lcore_acres_2013) %>% 
  mutate(m_core_change = replace_na(m_core_change, 0)) %>% 
  mutate(l_core_change = replace_na(l_core_change, 0))

# Subtract resulting prop from 1 to get percent change
county_percent_change <- county_frag_percent %>% 
  select(county, patch_change:l_core_change) %>% 
  mutate(patch_change = 1-patch_change) %>% 
  mutate(edge_change = 1-edge_change) %>% 
  mutate(s_core_change = 1-s_core_change) %>% 
  mutate(m_core_change = 1-m_core_change) %>% 
  mutate(l_core_change = 1-l_core_change) %>%   
  mutate(patch_change = patch_change*100) %>% 
  mutate(edge_change = 1-edge_change*100) %>% 
  mutate(s_core_change = 1-s_core_change*100) %>% 
  mutate(m_core_change = 1-m_core_change*100) %>% 
  mutate(l_core_change = 1-l_core_change*100) %>% 
  pivot_longer(!county, 
               names_to = "frag_type",
               values_to = "percent_change") %>% 
  mutate(frag_type = case_when(
    frag_type == "patch_change" ~ "Patch",
    frag_type == "edge_change" ~ "Edge",
    frag_type == "s_core_change" ~ "Small Core",
    frag_type == "m_core_change" ~ "Medium Core",
    frag_type == "l_core_change" ~ "Large Core"))

# Plot
#---------------------------------------
county_frag_percent <- ggplot(data = county_percent_change, aes(x = frag_type, y = percent_change)) +
  geom_col(aes(fill = frag_type)) +
  scale_fill_manual(values = frag_pallete2) +
  labs(title = "Fragment Type Percent Change Between 2013 and 2018",
       x = "Jurisdiction",
       y = "Percent of Forested Area") +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
  facet_wrap(~county, scales = "free_y") +
    theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    legend.title = element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title.align = 0.5,
    strip.background = element_rect(color = "grey40", fill = "grey30"),
    strip.text = element_text(size = 9, color = "white", face = "bold"),
    panel.border = element_rect(color = "grey40", fill = NA)
   ) +
    guides(fill = guide_legend(title = "Forest Fragment Type",
                               title.position = "top"))

county_frag_percent

ggsave(here("Graphics", "2_county_frag_change_percent.jpg"), county_frag_percent, height = 7)

# Facet by frag type instead of county
#---------------------------------------
county_fragtype_percent <- ggplot(data = county_percent_change, aes(x = county, y = percent_change)) +
  geom_col(aes(fill = county)) +
  scale_fill_manual(values = county_pallette) +
  labs(title = "Forest Fragment Percent Change Between 2013 and 2018",
       y = "Percent Change") +
  facet_wrap(~frag_type, scale = "free_y") +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
      theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    legend.title = element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title.align = 0.5,
    strip.background = element_rect(color = "grey40", fill = "grey30"),
    strip.text = element_text(size = 12, color = "white", face = "bold"),
    panel.border = element_rect(color = "grey40", fill = NA)
   ) +
    guides(fill = guide_legend(title = "Forest Fragment Type",
                               title.position = "top",
                               nrow = 4))

county_fragtype_percent

ggsave(here("Graphics", "2_county_fragtype_percent.jpg"), county_fragtype_percent, height = 7)

```


County 2018 Acres
```{r}
#---------------------------------------
# Fragmentation Acres 2018
#---------------------------------------
county_2018_acres <- county_frag %>% 
  select(county, patch_a_2018:lcore_a_2018) %>% 
  pivot_longer(!county, 
               names_to = "frag_type",
               values_to = "acres") %>% 
    mutate(frag_type = case_when(
    frag_type == "patch_a_2018" ~ "Patch",
    frag_type == "edge_a_2018" ~ "Edge",
    frag_type == "s_core_a_2018" ~ "Small Core",
    frag_type == "m_core_a_2018" ~ "Medium Core",
    frag_type == "lcore_a_2018" ~ "Large Core")) %>% 
  mutate(frag_type = as.factor(frag_type)) %>% 
  mutate(frag_type = fct_relevel(frag_type,
                              "Large Core",
                              "Medium Core",
                              "Small Core",
                              "Edge",
                              "Patch"))

# Pot
#---------------------------------------
county_frag_2018_plot <- ggplot(county_2018_acres, aes(x = frag_type, y = acres)) +
  geom_col(aes(fill = frag_type)) +
  scale_fill_manual(values = frag_pallete) +
  labs(title = "Forest Fragment Type Area 2018",
       y = "Area (acres)") +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
  facet_wrap(~county, scale = "free_y") +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    legend.title = element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title.align = 0.5,
    strip.background = element_rect(color = "grey40", fill = "grey30"),
    strip.text = element_text(size = 7.5, color = "white", face = "bold"),
    panel.border = element_rect(color = "grey40", fill = NA)
   ) +
    guides(fill = guide_legend(title = "Forest Fragment Type",
                               title.position = "top"))
county_frag_2018_plot

ggsave(here("Graphics", "2_county_frag_2018_acres.jpg"), county_frag_2018_plot, width = 7, height = 5.6)

```
County 2018 Frag Percent
```{r}
#---------------------------------------
# Fragmentation Percent 2018
#---------------------------------------

# Find sum acres of each county
county_acres_sum <- county_2018_acres %>% 
  group_by(county) %>%   
  summarise(tot_county_a = sum(acres))

# Join county sums and divide fragtype by total for proportion of each county
county_2018_percent <- county_2018_acres %>% 
  left_join(county_acres_sum, by = "county") %>% 
  mutate(percent = (acres/tot_county_a)*100) %>% 
  mutate(county = as.factor(county)) %>% 
  mutate(frag_type = fct_reorder(frag_type, desc(percent)))

#Plot
#---------------------------------------

# Stacked col
county_2018_percent_stack <- ggplot(data = county_2018_percent, aes(x = fct_rev(county), y = percent)) +
  geom_col(aes(fill = frag_type)) +
  scale_fill_manual(values = frag_pallete_stack) +
  labs(title = "Forest Proportion by Fragment Type 2018",
       x = "Jurisdiction",
       y = "Percent of Forested Area") +
  scale_y_continuous(breaks = c(0, 10, 25, 50, 75, 100),
                     labels = c("0%", "10%", "25%", "50%", "75%", "100%")) +
  theme_minimal() +
  coord_flip() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0), size = 14, face = "bold"),
    legend.title = element_text(size = 14, face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  guides(fill = guide_legend(title = "Forest Fragment Type"))

county_2018_percent_stack

ggsave(here("Graphics", "2_county_frag_percent.jpg"), county_2018_percent_stack)
  
```
County Proportions with State
```{r}
#---------------------------------------
# Fragmentation Percent 2018 State + County Merge
#---------------------------------------

# Wrangle
#---------------------------------------
# Add county column with "statewide"
state_frag_2018_percent$county <- "Statewide"

# Put columns in matching order
state_merge <- state_frag_2018_percent[,c("county", "frag_type", "acres", "percent")] 

# Remove total area column from county percents
county_merge <- county_2018_percent %>% 
  select(county, frag_type, acres, percent)

# Create Blank dummy row for and bind to county for separation purposes
dummy_row <- data.frame(
  county = " ",
frag_type = c("Large Core", "Medium Core", "Small Core", "Edge", "Patch"),
acres = 0,
percent = 0
)

county_merge_dummy <- rbind(county_merge, dummy_row)

# merge state and conty
state_county_merge <- rbind(state_merge, county_merge_dummy) %>% 
  mutate(county = as.factor(county)) %>%
  mutate(county = fct_relevel(county, "Statewide", " ", "")) %>% 
    mutate(frag_type = as.factor(frag_type)) %>% 
  mutate(frag_type = fct_relevel(frag_type,
                              "Large Core",
                              "Medium Core",
                              "Small Core",
                              "Edge",
                              "Patch")) %>%
  mutate(county = as.factor(county)) %>% 
  mutate(frag_type = fct_reorder(frag_type, desc(percent)))


# Plot
#---------------------------------------
county_2018_percent_merge <- ggplot(data = state_county_merge, aes(x = fct_rev(county), y = percent)) +
  geom_col(aes(fill = frag_type)) +
  scale_fill_manual(values = frag_pallete_stack) +
  labs(title = "Forest Proportion by Fragment Type 2018",
       x = "Jurisdiction",
       y = "Percent of Forested Area") +
  scale_y_continuous(breaks = c(0, 10, 25, 50, 75, 100),
                     labels = c("0%", "10%", "25%", "50%", "75%", "100%")) +
  theme_minimal() +
  coord_flip() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0), size = 14, face = "bold"),
    legend.title = element_text(size = 14, face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  guides(fill = guide_legend(title = "Forest Fragment Type"))

county_2018_percent_merge

# ggsave(here("Graphics", "2_county_frag_percent_merge.jpg"), county_2018_percent_merge)

```

County 2013 Frag Calculations
```{r}
#---------------------------------------
# Fragmentation Acres 2013
#---------------------------------------
county_2013_acres <- county_frag %>% 
  select(county, patch_a_2013:lcore_a_2013) %>% 
  pivot_longer(!county, 
               names_to = "frag_type",
               values_to = "acres") %>% 
    mutate(frag_type = case_when(
    frag_type == "patch_a_2013" ~ "Patch",
    frag_type == "edge_a_2013" ~ "Edge",
    frag_type == "s_core_a_2013" ~ "Small Core",
    frag_type == "m_core_a_2013" ~ "Medium Core",
    frag_type == "lcore_a_2013" ~ "Large Core")) %>% 
  mutate(frag_type = as.factor(frag_type)) %>% 
  mutate(frag_type = fct_relevel(frag_type,
                              "Large Core",
                              "Medium Core",
                              "Small Core",
                              "Edge",
                              "Patch"))

# Plot just for funzies
county_frag_2013_plot <- ggplot(county_2013_acres, aes(x = frag_type, y = acres)) +
  geom_col(aes(fill = frag_type)) +
  scale_fill_manual(values = frag_pallete) +
  labs(title = "Forest Fragment Type Area 2013",
       y = "Area (acres)") +
  theme_minimal() +
  geom_hline(aes(yintercept=0)) +
  facet_wrap(~county, scale = "free_y") +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    legend.title = element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title.align = 0.5,
    strip.background = element_rect(color = "grey40", fill = "grey30"),
    strip.text = element_text(size = 7.5, color = "white", face = "bold"),
    panel.border = element_rect(color = "grey40", fill = NA)
   ) +
    guides(fill = guide_legend(title = "Forest Fragment Type",
                               title.position = "top"))


ggsave(here("Graphics", "2_county_frag_acres_2013.jpg"), county_frag_2013_plot, width = 7, height = 5.6)

#---------------------------------------
# Fragmentation Percent 2013
#---------------------------------------
# Find sum acres of each county
county_acres_sum_2013 <- county_2013_acres %>% 
  group_by(county) %>%   
  summarise(tot_county_a = sum(acres))

# Join county sums and divide fragtype by total for proportion of each county
county_2013_percent <- county_2013_acres %>% 
  left_join(county_acres_sum, by = "county") %>% 
  mutate(percent = (acres/tot_county_a)*100) %>% 
  mutate(county = as.factor(county)) %>% 
  mutate(frag_type = fct_reorder(frag_type, desc(percent)))

# Plot
county_2013_percent_stack <- ggplot(data = county_2013_percent, aes(x = fct_rev(county), y = percent)) +
  geom_col(aes(fill = frag_type)) +
  scale_fill_manual(values = frag_pallete_stack) +
  labs(title = "Forest Proportion by Fragment Type 2013",
       x = "Jurisdiction",
       y = "Percent of Forested Area") +
  scale_y_continuous(breaks = c(0, 10, 25, 50, 75, 100),
                     labels = c("0%", "10%", "25%", "50%", "75%", "100%")) +
  theme_minimal() +
  coord_flip() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size = 14, face = "bold"),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0), size = 14, face = "bold"),
    legend.title = element_text(size = 14, face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  guides(fill = guide_legend(title = "Forest Fragment Type"))

county_2013_percent_stack

ggsave(here("Graphics", "2_county_frag_percent_2013.jpg"), county_2013_percent_stack, width = 7)

```

