---
title: "Updated Data"
author: "Marie Bouffard"
date: '2022-04-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Attach packages
library(tidyverse)
library(janitor)
library(here)
library(readxl)
library(scales)
library(stringr)

#---------------------------------------
# Read in Data
#---------------------------------------

# Task 1 
#---------------------------------------

# ---current lu---
# Read in 2018 state data
state_forest_raw <- read.csv(here("Data", "New", "1a_State.csv")) %>% 
  clean_names()

# Read in 2018 county data
county_forest_raw <- read.csv(here("Data", "New", "1a_County.csv")) %>% 
  clean_names()

# Old county data with population
county_pop <- read.csv(here("Data", "1a_County_short_2018.csv")) %>% 
  clean_names() %>% 
  select(county, x2020_pop)

# Read in 2018 county forest tree cover data
county_tc_forest_raw <- read_xlsx(here("Data", "New", "Figure4_PercentTC_TableToExcel.xlsx")) %>% 
  clean_names()

# ---lu change---
# Read in state 2013-2018 change data
state_change_raw <- read.csv(here("Data", "New", "1a_state_percentchange.csv")) %>% 
  clean_names()

# Task 3
#---------------------------------------

# Riparian tree cover data
riparian_raw <- read.csv(here("Data", "New", "3_riparian_county_2018.csv")) %>% 
  clean_names()

# Task 4
#---------------------------------------

# Read in state timber data
md_timber_raw <- read.csv(here("Data", "New", "4_MD_Timber.csv")) %>% 
  clean_names() %>% 
  mutate(county = str_squish(county)) # remove white space

#---------------------------------------
# Color  Palettes
#---------------------------------------

lu_palette_fig5 <- c(
  "#6eb663", # Forest Canopy, light green
  "#8DBE87", # Low veg, light green
  "#4059AD", # Water, royal blue
  "#F08701", # Impervious, orange 
  "#F9A620", # Roads, light orange
  "#D9682A", # Buildings/Structures, brick
  "#F9DB6D", # Barren, light yellow
  "#8CC8B5", # Shrub,light green-blue
  "#21A0A0"  # Wetland, Blue-green
)

lu_palette_fig25 <- c(
  "#F08701", # Impervious, orange 
  "#D9682A", # Buildings/Structures, brick
  "#F9DB6D", # Barren, light yellow
  "#4059AD", # Water, royal blue
  "#F9A620", # Roads, light orange
  "#21A0A0",  # Wetland, Blue-green
  "#8CC8B5", # Shrub,light green-blue
  "#8DBE87", # Low veg, light green
  "#6eb663" # Forest Canopy, light green
)

lu_palette_fig20 <- c(
  "#F9DB6D", # Barren, light yellow
  "#F08701", # Impervious, orange 
  "#8DBE87", # Low veg, light green
  "#F9A620", # Roads, light orange
  "#8CC8B5", # Shrub,light green-blue
  "#D9682A", # Buildings/Structures, brick
  "#6eb663", # Forest Canopy, light green
  "#4059AD", # Water, royal blue
  "#21A0A0"  # Wetland, Blue-green
)

# Categorical County Color Palette
county_pallette <- c("#68affc", "#485172", "#d6a7f0", "#7c46a0", "#20d8fd", "#155126", "#a2e84f", "#528f7a", "#7dd9a0", "#39970e", "#d0d9ae", "#e27040", "#f29180", "#e13224", "#922d4c", "#d9c937", "#fa217f", "#36f459", "#b825af", "#f27ff5", "#fda547", "#b7358d", "#a1e8af", "#7e52a0")

#---------------------------------------
# Functions
#---------------------------------------

# Use stringr::str_wrap() to create breaks in long facet titles
stwr <- function(string, nwrap = 15){
  paste(strwrap(string, width = nwrap), collapse = "\n")
}

stwr = Vectorize(stwr)

```

### Task 1a. 2018 forest stats

Land use proportion
```{r}
#---------------------------------------
# State level land use
#---------------------------------------

# Get percents 
state_lu_percent <- state_forest_raw %>% 
  select(can_a_acres:apg_a_acres, total_a_acres) %>% 
  pivot_longer(can_a_acres:road_a_acres, names_to = "lu", values_to = "acres") %>% 
  mutate(lu = case_when(
    lu == "can_a_acres" ~ "Tree Canopy",
    lu == "wet_a_acres" ~ "Wetland",
    lu == "low_veg_a_acres" ~ "Low Vegetation",
    lu == "shrub_a_acres" ~ "Shrub",
    lu == "barren_a_acres" ~ "Barren",
    lu == "water_a_acres" ~ "Water",
    lu == "struc_a_acres" ~ "Structures",
    lu == "road_a_acres" ~ "Road",
    lu == "imperv_a_acres" ~ "Impervious")) %>% 
  mutate(percent = acres/total_a_acres,
         label = scales::percent(percent)) %>% 
  mutate(lu = fct_reorder(lu, desc(percent))) %>% 
  select(lu:label)

state_lu_percent$name <- "Statewide"

#---------------------------------------
# County level land use
#---------------------------------------

# Get percents 
county_lu_percent <- county_forest_raw %>% 
  select(name, can_a_acres:road_a_acres) %>% 
  pivot_longer(can_a_acres:road_a_acres, names_to = "lu", values_to = "acres") %>% 
    mutate(lu = case_when(
    lu == "can_a_acres" ~ "Tree Canopy",
    lu == "wet_a_acres" ~ "Wetland",
    lu == "low_veg_a_acres" ~ "Low Vegetation",
    lu == "shrub_a_acres" ~ "Shrub",
    lu == "barren_a_acres" ~ "Barren",
    lu == "water_a_acres" ~ "Water",
    lu == "struc_a_acres" ~ "Structures",
    lu == "road_a_acres" ~ "Road",
    lu == "imperv_a_acres" ~ "Impervious",
    lu == "apg_a_acres" ~ "Aberdeen Proving Ground")) %>% 
  group_by(name) %>% 
  mutate(percent = acres/sum(acres)) %>% 
  mutate(percent = acres/sum(acres),
         label = scales::percent(percent, accuracy = 1)) # labels for county percent plot

#---------------------------------------
# Stacked bar plor lu percent area state and county
#---------------------------------------

# Merge state and county dfs
state_county_merge <- rbind(state_lu_percent, county_lu_percent) %>% 
  mutate(name = as.factor(name)) %>%  
  mutate(name= fct_relevel(name, "Statewide")) %>% 
  select(name, everything())

# Plot
#---------------------------------------
fig_5 <- ggplot(data = state_county_merge, aes(x = fct_rev(name), y = percent, fill = lu)) +
  geom_bar(position = "fill", stat = "identity") +
    labs(
#    title = "2018 Land Use Proportions by Jurisdiction",
    x = "Jurisdiction",
    y = "Percent Cover") +
    scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1),
                     labels = c("0%", "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%")) +
  scale_fill_manual(values = lu_palette_fig5) +
    theme_minimal() +
  theme(
#    plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.title = element_text(size = 14),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )+
  guides(fill = guide_legend(title = "Land Use Type")) +
  coord_flip()

fig_5

ggsave(here("Graphics", "fig5_state_county_lu.jpeg"), fig_5)

```

Percent tree canopy by county
```{r}
#---------------------------------------
# 2018 Percent Tree Canopy by County
#---------------------------------------

# Get tree cover by county
county_tree_cover <- county_lu_percent %>% 
  filter(lu == "Tree Canopy")

# Plot
#---------------------------------------
ggplot(data = county_tree_cover, aes(x = fct_rev(name), y = percent)) +
  geom_col(aes(fill = name)) +
  geom_text(aes(label = label,
                color = name,
                hjust = -0.1),
            size = 3) +
  scale_fill_manual(values = county_pallette) +
  scale_color_manual(values = county_pallette) +
  scale_y_continuous(breaks = c(0, 0.20, 0.40, 0.60, 0.80),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  labs(
 #   title = "Percent Tree Canopy by Jurisdiction 2018",
    x = "Jurisdiction",
    y = "Percent Tree Canopy"
  ) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position = "none",
#    plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 10, r = 0, b = 0, l = 0)),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

#---------------------------------------
# 2018 Percent Tree Canopy by County Inside vs Outside Forest
#---------------------------------------
county_tc_forest <- county_tc_forest_raw %>% 
  mutate(fore_pc_calc = forest_ac/jurisdicti) %>% # Calculate percent in forest
  mutate(tc_pc_calc = tc_out_fore/jurisdicti) %>% # Calculate percent out of forest
  select(name, fore_pc_calc, tc_pc_calc) %>% 
  pivot_longer(!name, 
               names_to = "type",
               values_to = "percent") %>% 
        mutate(type = case_when(
    type == "fore_pc_calc" ~ "Inside Forest",
    type == "tc_pc_calc" ~ "Outside Forest")) %>% 
  rename(county = name)

# Join population to county inside/outside forest data
county_tc_pop <- full_join(county_tc_forest, county_pop, by = "county") %>% 
  mutate(type = as.factor(type)) %>% 
  mutate(county = as.factor(county)) %>% 
  mutate(county = fct_reorder(county, x2020_pop)) # order by population (largest to smallest)

# Plot
#---------------------------------------
fig_4 <- ggplot(data = county_tc_pop, aes(x = county, y = percent)) +
  geom_col(aes(fill = type)) +
  scale_fill_manual(values = c("#24693d", "#6eb663")) +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  labs(
    x = "Jurisdiction",
    y = "Percent Tree Canopy Cover"
  ) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.title.y = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 10, r = 0, b = 0, l = 0)),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

fig_4
 
ggsave(here("Graphics", "fig4_county_lu.jpg"), fig_4)
```

Land use change at the state level
```{r}
#---------------------------------------
# State Land Use Change 2013 to 2018
#---------------------------------------

# Acres Change (Normalized)
#---------------------------------------

# Get area for each year
state_lu_2013 <- state_change_raw %>% 
  select(x2013_water_a:x2013_road_a) %>% 
  pivot_longer(x2013_water_a:x2013_road_a, 
               names_to = "lu",
               values_to = "lu_2013_m") %>% 
  mutate(lu = case_when(
    lu == "x2013_water_a" ~ "Water",
    lu == "x2013_wet_a" ~ "Wetland",
    lu == "x2013_can_a" ~ "Tree Canopy",
    lu == "x2013_shrub_a" ~ "Shrub",
    lu == "x2013_low_veg_a" ~ "Low Vegetation",
    lu == "x2013_barren_a" ~ "Barren",
    lu == "x2013_struc_a" ~ "Structures",
    lu == "x2013_imperv_a" ~ "Impervious",
    lu == "x2013_road_a" ~ "Road"))

state_lu_2018 <- state_change_raw %>% 
  select(water_a:road_a) %>% 
  pivot_longer(water_a:road_a,
               names_to = "lu",
               values_to = "lu_2018_m") %>% 
    mutate(lu = case_when(
    lu == "water_a" ~ "Water",
    lu == "wet_a" ~ "Wetland",
    lu == "can_a" ~ "Tree Canopy",
    lu == "shrub_a" ~ "Shrub",
    lu == "low_veg_a" ~ "Low Vegetation",
    lu == "barren_a" ~ "Barren",
    lu == "struc_a" ~ "Structures",
    lu == "imperv_a" ~ "Impervious",
    lu == "road_a" ~ "Road"))

# bind back together, convert meters to acres, calculate area change
state_change_acres <- left_join(state_lu_2013, state_lu_2018) %>% 
  mutate(lu_2013_acres = lu_2013_m*0.000247105) %>% 
  mutate(lu_2018_acres = lu_2018_m*0.000247105) %>% 
  mutate(acres_change = lu_2018_acres-lu_2013_acres) %>% 
  mutate(acres_change_std = acres_change/25914854725) %>% # divide by total area
  mutate(lu = fct_reorder(lu, desc(acres_change_std)))

# Plot
#---------------------------------------

# Acres Change
ggplot(data = state_change_acres, aes(x = lu, y = acres_change)) +
  geom_col(aes(fill = lu)) +
  labs(
#    title = "Normalized Statewide Area Change by Land Use",
    x = "Jurisdiction",
    y = "Area Change (Acres)"
  ) +
  scale_fill_manual(values = lu_palette_fig25) +
#  scale_y_continuous(labels = c()) +
  coord_flip() +
  theme_minimal() +
  theme(
#   plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.title = element_text(size = 14),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  ) +
guides(fill = guide_legend(title = "Land Use Type"))

# Acres Change Normalized
ggplot(data = state_change_acres, aes(x = lu, y = acres_change_std)) +
  geom_col(aes(fill = lu)) +
  labs(
#    title = "Normalized Statewide Area Change by Land Use",
    x = "Jurisdiction",
    y = "Magnitude of Change"
  ) +
  scale_fill_manual(values = lu_palette_fig25) +
#  scale_y_continuous(labels = c()) +
  coord_flip() +
  theme_minimal() +
  theme(
#   plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.title = element_text(size = 14),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  ) +
guides(fill = guide_legend(title = "Land Use Type"))

# Acres 2013 vs 2018------------------------------------------------------------------

state_change_compare <- state_change_acres %>% 
  select(lu, lu_2013_acres, lu_2018_acres, acres_change) %>% 
  pivot_longer(lu_2013_acres:lu_2018_acres, 
               names_to = "year",
               values_to = "tot_acres") %>% 
    mutate(net = case_when(
     acres_change >= 0 ~ "Gain",
     acres_change < 0 ~ "Loss"
   )) %>% 
  mutate(acres_change = round(acres_change, digits = 0)) %>% 
  mutate(year = case_when(
    year == "lu_2013_acres" ~ "2013",
    year == "lu_2018_acres" ~ "2018")) %>% 
  mutate(lu = fct_reorder(lu, desc(acres_change)))

###
fig_25_color <- ggplot(data = state_change_compare, aes(x = lu, y = tot_acres)) +
  geom_bar(aes(fill = lu, alpha = year),
           position="dodge", stat="identity")+
  scale_fill_manual(values = lu_palette_fig25) +
  scale_alpha_manual(values = c(0.3, 1)) +
    annotate("text",
           x = 1, y = 300000,
           label = "+10,809", color = "#498D43") +
  annotate("text",
           x = 2, y = 200000,
           label = "+4,687", color = "#498D43") +
  annotate("text",
           x = 3, y = 150000,
           label = "+4,269", color = "#498D43") +
    annotate("text",
           x = 4, y = 350000,
           label = "+642", color = "#498D43") +
    annotate("text",
           x = 5, y = 220000,
           label = "+508", color = "#498D43") +
      annotate("text",
           x = 6, y = 275000,
           label = "-214", color = "red") +
      annotate("text",
           x = 7, y = 125000,
           label = "-891", color = "red") +
      annotate("text",
           x = 8, y = 2470000,
           label = "-7,019", color = "red") +
      annotate("text",
           x = 9, y = 3190000,
           label = "-12792", color = "red") +
  scale_y_continuous(breaks = c(0, 1000000, 2000000, 3000000),
                     labels = c("0", "1,000,000", "2,000,000", "3,000,000")) +
  labs(
    x = "Land Use",
    y = "Total Area (Acres)"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.title.y = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 10, r = 0, b = 0, l = 0)),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  ) +
  guides(fill = "none")

fig_25_color

# ggsave(here("Graphics", "fig25_color.jpg"), fig_25_color, height = 5, width = 9)

###

fig_25 <- ggplot(data = state_change_compare, aes(x = lu, y = tot_acres)) +
  geom_bar(aes(fill = year), position="dodge", stat="identity") +
  # geom_text(aes(label = acres_change, color = net, vjust = -0.5)) +
  annotate("text",
           x = 1, y = 300000,
           label = "+10,809", color = "#498D43") +
  annotate("text",
           x = 2, y = 200000,
           label = "+4,687", color = "#498D43") +
  annotate("text",
           x = 3, y = 150000,
           label = "+4,269", color = "#498D43") +
    annotate("text",
           x = 4, y = 350000,
           label = "+642", color = "#498D43") +
    annotate("text",
           x = 5, y = 220000,
           label = "+508", color = "#498D43") +
      annotate("text",
           x = 6, y = 275000,
           label = "-214", color = "red") +
      annotate("text",
           x = 7, y = 125000,
           label = "-891", color = "red") +
      annotate("text",
           x = 8, y = 2470000,
           label = "-7,019", color = "red") +
      annotate("text",
           x = 9, y = 3190000,
           label = "-12,792", color = "red") +
  scale_fill_manual(values = c("gray70", "gray40")) +
  # scale_color_manual(values = c("green", "red")) +
  # scale_alpha_manual(values = c(1, 0.5)) + 
  scale_y_continuous(breaks = c(0, 1000000, 2000000, 3000000),
                     labels = c("0", "1,000,000", "2,000,000", "3,000,000")) +
  labs(
    x = "Land Cover Class",
    y = "Total Area (Acres)"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.title.y = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 10, r = 0, b = 0, l = 0)),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

fig_25

ggsave(here("Graphics", "fig25_state_lu_change.jpg"), fig_25, height = 5, width = 9)


```

Land use change at the county level
```{r}

#---------------------------------------
# 2013-2018 Land Use by County
#---------------------------------------

# Get 2013 lu by county
county_lu_2013 <- county_forest_raw %>% 
  select(name:x2013_road_a) %>% 
  pivot_longer(!name, names_to = "lu", values_to = "lu_2013_m") %>% 
    mutate(lu = case_when(
    lu == "x2013_water_a" ~ "Water",
    lu == "x2013_wet_a" ~ "Wetland",
    lu == "x2013_can_a" ~ "Tree Canopy",
    lu == "x2013_shrub_a" ~ "Shrub",
    lu == "x2013_low_veg_a" ~ "Low Vegetation",
    lu == "x2013_barren_a" ~ "Barren",
    lu == "x2013_struc_a" ~ "Structures",
    lu == "x2013_imperv_a" ~ "Impervious",
    lu == "x2013_road_a" ~ "Road"))

# Get 2018 lu by county 
county_lu_2018 <- county_forest_raw %>% 
  select(name, water_a:road_a) %>% 
  pivot_longer(!name, names_to = "lu", values_to = "lu_2018_m") %>% 
      mutate(lu = case_when(
    lu == "water_a" ~ "Water",
    lu == "wet_a" ~ "Wetland",
    lu == "tc_a" ~ "Tree Canopy",
    lu == "shrub_a" ~ "Shrub",
    lu == "low_veg_a" ~ "Low Vegetation",
    lu == "barren_a" ~ "Barren",
    lu == "struc_a" ~ "Structures",
    lu == "imperv_a" ~ "Impervious",
    lu == "road_a" ~ "Road"))

# Bind back together, get area in acres, calculate change
county_lu_change <- left_join(county_lu_2013, county_lu_2018) %>% 
  mutate(lu_2013_acres = lu_2013_m*0.000247105) %>% 
  mutate(lu_2018_acres = lu_2018_m*0.000247105) %>% 
  mutate(acres_change = lu_2018_acres-lu_2013_acres)

# Plot
#---------------------------------------
fig_20 <- ggplot(data = county_lu_change, aes(x = lu, y = acres_change)) +
  geom_col(aes(fill = lu)) +
  facet_wrap(~name, scales = "free") +
  scale_fill_manual(values = lu_palette_fig20) +
  labs(
    x = "Land Cover Class",
    y = "Area Change (Acres)"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank(),
    strip.background = element_rect(color = "grey40", fill = "grey30"),
    strip.text = element_text(color = "white", face = "bold"),
    panel.border = element_rect(color = "grey40", fill = NA),
    axis.title.y = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 10, r = 0, b = 0, l = 0)),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

fig_20

ggsave(here("Graphics", "fig20_county_lu_change.jpg"), fig_20, height = 7.5, width = 8)

```


### Task 3 Urban Change

Percent tree canopy in riparian buffer zone by jurisdiction
```{r}
#---------------------------------------
# Riparian buffer tree canopy
#---------------------------------------

# Calc percent and Create new variable: above or below threshold
riparian_buffer <- riparian_raw %>% 
  select(name, can_a, total_a) %>% 
  mutate(can_p_calc = can_a/total_a,
         label = scales::percent(can_p_calc, accuracy = 1)) %>% 
  mutate(threshold = case_when(
     label >= 70 ~ "Meets Goal",
     label < 70 ~ "Does Not Meet Goal"
   ))

# Plot
#---------------------------------------
fig_16 <- ggplot(data = riparian_buffer, aes(x = fct_rev(name), y = can_p_calc)) +
  geom_col(aes(fill = threshold)) +
  scale_fill_manual(values = c("#c3dbcb", "seagreen4")) +
  labs(
#    title = "Riparian Buffer Percent Tree Canopy",
    x = "Jurisdiction",
    y = "Percent Tree Canopy over Land Area") +
  geom_text(label = "70%",
            color = "red",
            face = "bold",
            vjust = 12.85,
            aes(x = "Kent",y = 0.70)) +
  geom_hline(aes(yintercept = 0.70), linetype = "dashed",
            color = "red",
            size = 1) +
  geom_text(aes(label = label,
                hjust = -0.1),
            size = 3) +
  scale_y_continuous(breaks = c(0, 0.20, 0.40, 0.60, 0.80),
                     labels = c("0%", "20%", "40%", "60%", "80%")) +
  coord_flip(clip = "off") +
  theme_minimal() +
  theme(
#    plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.position = "bottom",
    legend.title = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

fig_16

ggsave(here("Graphics", "fig16_riparian.jpg"), fig_16, height = 7, width = 8)

```


### Task 4 Projected Land Use

Total timber harvest by county 2013 to 2021
```{r}
#---------------------------------------
# Total timber harvest by county
#---------------------------------------

# Get total acres harvested between 2013 and 2021
timber_total <- md_timber_raw %>% 
  group_by(county) %>% 
  summarise(tot_acres = sum(forest_harvest_acres))

# Plot
#---------------------------------------
fig_21 <- ggplot(data = timber_total, aes(x = fct_rev(county), y = tot_acres)) +
  geom_col(aes(fill = county)) +
  scale_fill_manual(values = county_pallette) +
  labs(
#    title = "Total Timber Harvest by Jurisdiction \n between 2013 and 2021",
    x = "Jurisdiction",
    y = "Forest Harvested (Acres)"
  ) +
    scale_y_continuous(breaks = c(0, 10000, 20000),
                     labels = c("0", "10,000", "20,000")) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position = "none",
#    plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 10, r = 0, b = 0, l = 0)),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

fig_21

ggsave(here("Graphics", "fig21_timber.jpg"), fig_21)

#---------------------------------------
# Ordered by population
#---------------------------------------
# Join timber total and population data
timber_pop <- full_join(timber_total, county_pop, by = "county") %>% 
  mutate(county = as.factor(county)) %>% 
  mutate(county = fct_reorder(county, x2020_pop)) # order by population (largest to smallest)

# Plot
#---------------------------------------
fig_21_pop <- ggplot(data = timber_pop, aes(x = county, y = tot_acres)) +
  geom_col(aes(fill = county)) +
  scale_fill_manual(values = county_pallette) +
  labs(
#    title = "Total Timber Harvest by Jurisdiction \n between 2013 and 2021",
    x = "Jurisdiction",
    y = "Forest Harvested (Acres)"
  ) +
    scale_y_continuous(breaks = c(0, 10000, 20000),
                     labels = c("0", "10,000", "20,000")) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position = "none",
#    plot.title = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 0, r = 10, b = 0, l = 0)),
    axis.title.x = element_text(size = 14,
                                face = "bold",
                                margin = margin(t = 10, r = 0, b = 0, l = 0)),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

fig_21_pop

ggsave(here("Graphics", "fig21_timber_pop.jpg"), fig_21_pop)

```

